import { useState } from 'react';
import { API_KEY_SCOPES,API_KEY_SCOPE_LABELS,WEBHOOK_EVENT_TYPES,type ApiKeyScope,type PlatformWebhookEventType,type CreateApiKeyInput,type CreateWebhookSubscriptionInput } from '@erp/shared';
import { Button } from '../../components/ui/Button';
import { Card,CardHeader,PageHeader } from '../../components/ui/Card';
import { Field,Input,Select } from '../../components/ui/Field';
import { Callout,PageLoading } from '../../components/ui/Feedback';
import { useToast } from '../../components/ui/Toast';
import { errorMessage } from '../../lib/errors';
import { useCan,useCMutation,useCQuery } from '../../lib/queries';
import { useCompany } from '../../lib/session';

interface Branch {id:string;name:string;isActive:boolean;}
interface Key {id:string;name:string;lastFour:string;scopes:ApiKeyScope[];branchId:string|null;expiresAt:string;revokedAt:string|null;lastUsedAt:string|null;}
interface Subscription {id:string;name:string;url:string;branchId:string|null;eventTypes:PlatformWebhookEventType[];secretVersion:number;enabled:boolean;revokedAt:string|null;}
interface Delivery {id:string;eventType:PlatformWebhookEventType;status:string;attempts:number;createdAt:string;deliveredAt:string|null;lastHttpStatus:number|null;lastError:string|null;nextAttemptAt:string;invoiceId:string;}
const eventNames:Record<PlatformWebhookEventType,string>={'invoice.draft.created':'Fatura taslağı oluşturuldu','invoice.posted':'Fatura kesinleştirildi'};
const statusNames:Record<string,string>={pending:'Tekrar denenecek',sending:'Gönderiliyor',delivered:'Teslim edildi',dead_letter:'Teslim durdu',cancelled:'İptal edildi'};
const date=(value:string|null)=>value?new Date(value).toLocaleString('tr-TR'):'Henüz yok';

export function PlatformIntegrationsPage(){
 const company=useCompany(),can=useCan(),toast=useToast(),editable=can('core.integrations.manage');
 const keys=useCQuery<{keys:Key[]}>(['platform-keys'],'/api/company/api-keys',{branchId:'all'});
 const subscriptions=useCQuery<{subscriptions:Subscription[]}>(['platform-webhooks'],'/api/company/webhook-subscriptions',{branchId:'all'});
 const branches=useCQuery<{branches:Branch[]}>(['branches'],'/api/company/branches',{branchId:'all'});
 const [name,setName]=useState(''),[days,setDays]=useState('90'),[branch,setBranch]=useState(''),[scopes,setScopes]=useState<ApiKeyScope[]>(['invoices.read']);
 const [hookName,setHookName]=useState(''),[url,setUrl]=useState(''),[hookBranch,setHookBranch]=useState(''),[events,setEvents]=useState<PlatformWebhookEventType[]>(['invoice.posted']);
 const [revealed,setRevealed]=useState<{label:string;value:string}|null>(null),[selected,setSelected]=useState('');
 const deliveries=useCQuery<{deliveries:Delivery[]}>(['platform-deliveries',selected],selected?`/api/company/webhook-subscriptions/${selected}/deliveries`:null,{branchId:'all',refetchInterval:15000});
 const createKey=useCMutation((body:CreateApiKeyInput,call)=>call<{id:string;token:string}>('/api/company/api-keys',{method:'POST',body,branchId:'all'}),[['platform-keys']]);
 const createHook=useCMutation((body:CreateWebhookSubscriptionInput,call)=>call<{subscription:Subscription;secret:string}>('/api/company/webhook-subscriptions',{method:'POST',body,branchId:'all'}),[['platform-webhooks']]);
 const keyRevoke=useCMutation((id:string,call)=>call(`/api/company/api-keys/${id}/revoke`,{method:'POST',branchId:'all'}),[['platform-keys']]);
 const hookAction=useCMutation(({id,action,enabled}:{id:string;action:'toggle'|'revoke'|'rotate-secret';enabled?:boolean},call)=>call<{secret?:string}>(`/api/company/webhook-subscriptions/${id}${action==='toggle'?'':'/'+action}`,{method:action==='toggle'?'PATCH':'POST',body:action==='toggle'?{enabled}:undefined,branchId:'all'}),[['platform-webhooks']]);
 const retry=useCMutation((id:string,call)=>call(`/api/company/webhook-deliveries/${id}/retry`,{method:'POST',branchId:'all'}),[['platform-deliveries',selected]]);
 const action=async(fn:()=>Promise<unknown>,message:string)=>{try{await fn();toast.success(message);}catch(error){toast.error(errorMessage(error));}};
 const branchName=(id:string|null)=>id?branches.data?.branches.find(b=>b.id===id)?.name??'Şube':'Şubeye atanmamış';
 const branchOptions=<><option value="">Şubeye atanmamış kayıtlar</option>{branches.data?.branches.filter(b=>b.isActive).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</>;
 if(keys.isPending||subscriptions.isPending)return <PageLoading/>;
 if(keys.error||subscriptions.error)return <Callout tone="danger">{errorMessage(keys.error??subscriptions.error)}</Callout>;
 return <>
  <PageHeader title="API ve bildirim bağlantıları" description="Diğer uygulamalara sınırlı şirket erişimi verin ve fatura olaylarını imzalı bildirimle iletin."/>
  <div className="space-y-5">
   <Callout>Her bağlantı tek şube veya şubeye atanmamış kayıtlar için çalışır. Oluşturan kişinin güncel yetkileri her kullanımda denetlenir. API yalnız taslak satış faturası oluşturabilir; kesinleştirme uygulamadaki onay sürecinden geçer.</Callout>
   {revealed&&<Card><CardHeader title={revealed.label} description="Bu gizli değer yalnız şimdi gösterilir. Bağlantıyı kuracak uygulamaya güvenli şekilde aktarın."/><div className="space-y-3 p-5"><code className="block select-all break-all rounded-lg bg-surface-2 p-3 text-sm">{revealed.value}</code><div className="flex flex-wrap gap-2"><Button onClick={()=>void action(()=>navigator.clipboard.writeText(revealed.value),'Kopyalandı')}>Kopyala</Button><Button variant="ghost" onClick={()=>setRevealed(null)}>Gizle</Button></div></div></Card>}
   {editable&&<div className="grid gap-5 xl:grid-cols-2">
    <Card><CardHeader title="API anahtarı oluştur"/><form className="space-y-4 p-5" onSubmit={async e=>{e.preventDefault();try{const result=await createKey.mutateAsync({name,branchId:branch||null,scopes,expiresAt:new Date(Date.now()+Number(days)*86400000).toISOString()});setRevealed({label:'Yeni API anahtarı',value:result.token});setName('');toast.success('API anahtarı oluşturuldu');}catch(error){toast.error(errorMessage(error));}}}>
     <Field label="Bağlantı adı" required>{id=><Input id={id} value={name} onChange={e=>setName(e.target.value)} required minLength={2} maxLength={100} placeholder="Depo uygulaması"/>}</Field>
     <div className="grid gap-4 sm:grid-cols-2"><Field label="Şube">{id=><Select id={id} value={branch} onChange={e=>setBranch(e.target.value)}>{branchOptions}</Select>}</Field><Field label="Geçerlilik süresi (gün)">{id=><Input id={id} type="number" value={days} min={1} max={365} required onChange={e=>setDays(e.target.value)}/>}</Field></div>
     <fieldset className="space-y-2"><legend className="mb-2 text-sm">İzin verilen işlemler</legend>{API_KEY_SCOPES.map(scope=><label key={scope} className="flex items-start gap-2 text-sm"><input type="checkbox" className="mt-0.5 size-4 shrink-0" checked={scopes.includes(scope)} onChange={()=>setScopes(scopes.includes(scope)?scopes.filter(s=>s!==scope):[...scopes,scope])}/>{API_KEY_SCOPE_LABELS[scope]}</label>)}</fieldset>
     <Button type="submit" variant="primary" loading={createKey.isPending} disabled={!scopes.length}>Anahtar oluştur</Button>
    </form></Card>
    <Card><CardHeader title="İmzalı bildirim bağlantısı" description="Fatura olayı oluşunca belirttiğiniz HTTPS adresine gönderilir."/><form className="space-y-4 p-5" onSubmit={async e=>{e.preventDefault();try{const result=await createHook.mutateAsync({name:hookName,url,branchId:hookBranch||null,eventTypes:events});setRevealed({label:'Bildirim imza anahtarı',value:result.secret});setSelected(result.subscription.id);setHookName('');setUrl('');toast.success('Bildirim bağlantısı oluşturuldu');}catch(error){toast.error(errorMessage(error));}}}>
     <Field label="Bağlantı adı" required>{id=><Input id={id} value={hookName} onChange={e=>setHookName(e.target.value)} minLength={2} maxLength={100} required placeholder="Sipariş sistemi"/>}</Field>
     <Field label="HTTPS alıcı adresi" required>{id=><Input id={id} type="url" value={url} onChange={e=>setUrl(e.target.value)} maxLength={2000} required placeholder="https://ornek.com/erp-bildirim"/>}</Field>
     <Field label="Şube">{id=><Select id={id} value={hookBranch} onChange={e=>setHookBranch(e.target.value)}>{branchOptions}</Select>}</Field>
     <fieldset className="space-y-2"><legend className="mb-2 text-sm">Gönderilecek olaylar</legend>{WEBHOOK_EVENT_TYPES.map(event=><label key={event} className="flex items-start gap-2 text-sm"><input type="checkbox" className="mt-0.5 size-4 shrink-0" checked={events.includes(event)} onChange={()=>setEvents(events.includes(event)?events.filter(v=>v!==event):[...events,event])}/>{eventNames[event]}</label>)}</fieldset>
     <Button type="submit" variant="primary" loading={createHook.isPending} disabled={!events.length}>Bağlantı oluştur</Button>
    </form></Card>
   </div>}
   <Card><CardHeader title="API anahtarları"/><div className="space-y-3 p-5">{keys.data?.keys.map(key=><div key={key.id} className="flex min-w-0 flex-wrap items-start justify-between gap-3 rounded-lg border border-border p-4"><div className="min-w-0 flex-1"><p className="break-words font-medium">{key.name} <span className="text-sm text-muted">…{key.lastFour}</span></p><p className="text-sm text-muted">{branchName(key.branchId)} · {key.revokedAt?'İptal edildi':new Date(key.expiresAt)<=new Date()?'Süresi doldu':'Etkin'}</p><p className="mt-1 break-words text-xs text-muted">{key.scopes.map(s=>API_KEY_SCOPE_LABELS[s]).join(' · ')}</p><p className="mt-2 text-xs text-muted">Son kullanım: {date(key.lastUsedAt)} · Bitiş: {date(key.expiresAt)}</p></div>{editable&&!key.revokedAt&&<Button loading={keyRevoke.isPending} variant="ghost" onClick={()=>void action(()=>keyRevoke.mutateAsync(key.id),'API anahtarı iptal edildi')}>İptal et</Button>}</div>)}{!keys.data?.keys.length&&<p className="text-sm text-muted">Henüz API anahtarı oluşturulmadı.</p>}</div></Card>
   <Card><CardHeader title="Bildirim bağlantıları"/><div className="space-y-3 p-5">{subscriptions.data?.subscriptions.map(hook=><div key={hook.id} className="min-w-0 rounded-lg border border-border p-4"><p className="break-words font-medium">{hook.name}</p><p className="mt-1 break-all text-sm text-muted">{hook.url}</p><p className="mt-1 text-xs text-muted">{branchName(hook.branchId)} · {hook.revokedAt?'İptal edildi':hook.enabled?'Etkin':'Durduruldu'} · İmza sürümü {hook.secretVersion}</p><p className="mt-1 text-xs text-muted">{hook.eventTypes.map(e=>eventNames[e]).join(' · ')}</p><div className="mt-3 flex flex-wrap gap-2"><Button onClick={()=>setSelected(hook.id)}>Teslim geçmişi</Button>{editable&&!hook.revokedAt&&<><Button variant="ghost" loading={hookAction.isPending} onClick={()=>void action(()=>hookAction.mutateAsync({id:hook.id,action:'toggle',enabled:!hook.enabled}),'Bildirim durumu güncellendi')}>{hook.enabled?'Durdur':'Etkinleştir'}</Button><Button variant="ghost" disabled={hookAction.isPending} onClick={()=>void action(async()=>{const result=await hookAction.mutateAsync({id:hook.id,action:'rotate-secret'});if(result.secret)setRevealed({label:'Yeni bildirim imza anahtarı',value:result.secret});},'İmza anahtarı yenilendi')}>İmza anahtarını yenile</Button><Button variant="ghost" disabled={hookAction.isPending} onClick={()=>void action(()=>hookAction.mutateAsync({id:hook.id,action:'revoke'}),'Bildirim bağlantısı iptal edildi')}>İptal et</Button></>}</div></div>)}{!subscriptions.data?.subscriptions.length&&<p className="text-sm text-muted">Henüz bildirim bağlantısı oluşturulmadı.</p>}</div></Card>
   {selected&&<Card><CardHeader title="Bildirim teslim geçmişi" description="Aynı olay tekrar denenirken olay kimliği ve içeriği korunur. Alıcı aynı kimliği ikinci kez işlememelidir."/><div className="space-y-3 p-5">{deliveries.isPending&&<PageLoading/>}{deliveries.error&&<Callout tone="danger">{errorMessage(deliveries.error)}</Callout>}{deliveries.data?.deliveries.map(delivery=><div key={delivery.id} className="min-w-0 rounded-lg border border-border p-4"><p className="font-medium">{eventNames[delivery.eventType]} · {statusNames[delivery.status]??delivery.status}</p><p className="mt-1 text-xs text-muted">{date(delivery.createdAt)} · {delivery.attempts} deneme{delivery.lastHttpStatus?' · HTTP '+delivery.lastHttpStatus:''}</p><p className="mt-1 break-all text-xs text-muted">Olay: {delivery.id}</p>{delivery.lastError&&<p className="mt-2 break-words text-sm text-danger">{delivery.lastError}</p>}{editable&&['dead_letter','cancelled'].includes(delivery.status)&&<Button className="mt-3" loading={retry.isPending} onClick={()=>void action(()=>retry.mutateAsync(delivery.id),'Bildirim yeniden denemeye alındı')}>Yeniden dene</Button>}</div>)}{deliveries.data&&!deliveries.data.deliveries.length&&<p className="text-sm text-muted">Bu bağlantıya henüz olay gönderilmedi.</p>}</div></Card>}
   <Card><CardHeader title="Bağlantıyı kuracak geliştirici için"/><div className="space-y-3 p-5 text-sm"><p>İstekler <code>Authorization: Bearer …</code> ile gönderilir. Listeleme adresleri:</p><code className="block break-all rounded-lg bg-surface-2 p-3">/api/integration/v1/companies/{company.id}/items<br/>/api/integration/v1/companies/{company.id}/parties<br/>/api/integration/v1/companies/{company.id}/invoices</code><p>Taslak oluştururken faturalar adresine POST isteği ve UUID biçiminde <code>Idempotency-Key</code> başlığı gönderin. Aynı kimlikle farklı içerik reddedilir. <code>post</code> alanı kabul edilmez.</p><p>Bildirim imzası <code>x-erp-signature</code> başlığında HMAC-SHA256 olarak gelir. İmzalanan metin: <code className="break-all">timestamp + '.' + eventId + '.' + rawBody</code>. Alıcı imzayı, <code>x-erp-timestamp</code> tazeliğini ve <code>x-erp-event-id</code> tekrarlarını doğrulamalıdır.</p></div></Card>
  </div>
 </>;
}
