import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Badge } from '../../components/ui/Badge';
import { useConfirmation } from '../../components/ui/useConfirmation';
import { Button } from '../../components/ui/Button';
import { Card } from '../../components/ui/Card';
import { Callout, PageLoading } from '../../components/ui/Feedback';
import { Table, TableWrap, Td, Th, Tr } from '../../components/ui/Table';
import { useToast } from '../../components/ui/Toast';
import { api } from '../../lib/api';
import { errorMessage } from '../../lib/errors';
import { useCQuery } from '../../lib/queries';

interface SessionRow { id: string; startedAt: string; lastRenewedAt: string; expiresAt: string; userAgent: string | null; ip: string | null; current: boolean }
const dateTime = (value: string) => new Date(value).toLocaleString('tr-TR');
export function SessionsCard() {
  const toast = useToast();
  const qc = useQueryClient();
  const { confirm, dialog } = useConfirmation();
  const query = useQuery({ queryKey: ['auth-sessions'], queryFn: () => api<{ sessions: SessionRow[] }>('/api/auth/sessions'), refetchOnWindowFocus: true });
  const revoke = useMutation({ mutationFn: (id: string) => api(`/api/auth/sessions/${id}`, { method: 'DELETE' }), onSuccess: () => { void qc.invalidateQueries({ queryKey: ['auth-sessions'] }); toast.success('Oturum kapatıldı'); }, onError: error => toast.error(errorMessage(error)) });
  const others = useMutation({ mutationFn: () => api('/api/auth/sessions/revoke-others', { method: 'POST' }), onSuccess: () => { void qc.invalidateQueries({ queryKey: ['auth-sessions'] }); toast.success('Diğer oturumlar kapatıldı'); }, onError: error => toast.error(errorMessage(error)) });
  return <Card className="mt-5 flex flex-col gap-3 p-5">{dialog}<div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-base">Açık oturumlarım</h2><p className="text-sm text-muted">Oturum kapatıldığında o oturumun erişim ve yenileme belirteçleri geçersizleşir.</p></div><Button disabled={!query.data?.sessions.some(s => !s.current) || revoke.isPending} loading={others.isPending} onClick={() => confirm({ title: 'Diğer oturumları kapat', description: 'Diğer tüm açık oturumlarınızın erişim ve yenileme belirteçleri geçersizleşir.', confirmLabel: 'Oturumları kapat', danger: true, onConfirm: () => others.mutateAsync() })}>Diğer oturumları kapat</Button></div>
    {query.isPending ? <PageLoading /> : query.error ? <Callout tone="danger">{errorMessage(query.error)}</Callout> : <ul className="divide-y divide-border">{query.data?.sessions.map(session => <li key={session.id} className="flex flex-col gap-2 py-3 sm:flex-row sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="text-sm">{session.ip ?? 'IP bilgisi yok'}</span>{session.current && <Badge tone="success">Bu oturum</Badge>}</div><p className="mt-1 break-words text-xs text-muted">{session.userAgent ?? 'Tarayıcı bilgisi yok'}</p><p className="mt-1 text-xs text-muted">Başlangıç: {dateTime(session.startedAt)} · Son yenileme: {dateTime(session.lastRenewedAt)}</p></div>{!session.current && <Button className="self-start shrink-0" size="sm" disabled={others.isPending} loading={revoke.isPending && revoke.variables === session.id} onClick={() => revoke.mutate(session.id)}>Oturumu kapat</Button>}</li>)}</ul>}
  </Card>;
}

const REPORT_LABELS: Record<string, string> = {
  'trial-balance': 'Mizan', 'year-end-closing': 'Yıl sonu kapanışı', 'account-ledger': 'Hesap ekstresi', 'party-aging': 'Cari yaşlandırma', 'party-statement': 'Cari ekstre', 'party-open-items': 'Cari açık kalemler', 'stock-status': 'Stok durumu', 'stock-analytics': 'Stok analizi', 'supplier-performance': 'Tedarikçi performansı', 'item-card': 'Stok kartı', 'vat-summary': 'KDV özeti', 'treasury-statement': 'Kasa/banka ekstresi', 'journal-book': 'Yevmiye defteri', 'general-ledger': 'Büyük defter', 'sales-report': 'Satış raporu', 'purchase-report': 'Alış raporu', 'item-profitability': 'Ürün kârlılığı', 'fx-differences': 'Kur farkları', 'bank-reconciliation': 'Banka mutabakatı', 'project-cost-report': 'Proje maliyeti', 'project-cost-by-code': 'Kodlara göre proje maliyeti', 'subcontract-register': 'Taşeron sözleşmeleri', 'project-profitability': 'Proje kârlılığı', 'cash-forecast': 'Nakit projeksiyonu', 'real-estate-units': 'Bağımsız bölümler', 'sales-contracts': 'Satış sözleşmeleri', 'sales-schedule': 'Satış ödeme planı', 'overdue-installments': 'Gecikmiş taksitler', 'progress-payments': 'Hakedişler', 'employees': 'Personel listesi', 'attendance-summary': 'Puantaj özeti', 'attendance-labor': 'İşçilik raporu', 'payroll-register': 'Bordro listesi', 'payroll-cost': 'Bordro maliyeti', 'directory-contacts': 'Rehber kişiler', 'directory-organizations': 'Rehber kuruluşlar', 'agenda': 'Ajanda', 'employee-balances': 'Personel bakiyeleri', 'employee-advances': 'Personel avansları', 'employee-statement': 'Personel ekstresi', 'social-declaration': 'Sosyal güvenlik bildirgesi', 'social-premium-summary': 'Prim özeti', 'cheques': 'Çek ve senetler', 'cheque-maturity': 'Çek vadeleri', 'cheques-due': 'Vadesi gelen çekler', 'cheques-bounced': 'Karşılıksız çekler', 'sales-docs': 'Satış belgeleri', 'import-files': 'İthalat dosyaları', 'import-file-report': 'İthalat dosya raporu', 'import-landed-items': 'İthalat ürün maliyetleri', 'expense-entries': 'Gider kayıtları', 'expense-report': 'Gider raporu', 'serials': 'Seri ve parti kayıtları', 'price-list-items': 'Fiyat listesi', 'party-prices': 'Cari fiyatları', 'delivery-notes': 'İrsaliyeler', 'bank-guarantees': 'Banka teminatları', 'foreign-documents': 'Yabancı çalışan belgeleri', 'foreign-guarantees': 'Yabancı çalışan teminatları', 'variation-orders': 'Değişiklik emirleri', 'variation-order': 'Değişiklik emri', 'projects-summary': 'Proje özeti', 'fx-position': 'Döviz pozisyonu', 'executive-summary': 'Yönetici özeti', 'full-data': 'Tüm şirket verileri',
};
interface ExportEvent { id: string; reportKey: string; format: string; rowCount: number; occurredAt: string; requestId: string; fullName: string }
export function ExportActivityCard() {
  const query = useCQuery<{ events: ExportEvent[] }>(['export-events'], '/api/company/export-events', { refetchOnWindowFocus: true });
  return <Card className="mt-5 flex flex-col gap-3 p-5"><h2 className="text-base">Şirket dışa aktarma geçmişi</h2><p className="text-sm text-muted">Son 100 dosya hazırlama kaydı. Yönetici tüm üyeleri, diğer kullanıcılar kendi kayıtlarını görür. Satır sayısı veri satırlarını gösterir; istemcinin dosyayı kaydettiğini doğrulamaz.</p>
    {query.isPending ? <PageLoading /> : query.error ? <Callout tone="danger">{errorMessage(query.error)}</Callout> : !query.data?.events.length ? <p className="text-sm text-muted">Henüz dosya hazırlama kaydı yok.</p> : <TableWrap><Table><thead><tr><Th>Tarih</Th><Th>Kullanıcı</Th><Th>Rapor</Th><Th>Biçim</Th><Th>Satır</Th></tr></thead><tbody>{query.data.events.map(event => <Tr key={event.id}><Td>{dateTime(event.occurredAt)}</Td><Td>{event.fullName}</Td><Td title={`İstek: ${event.requestId}`}>{REPORT_LABELS[event.reportKey] ?? (event.reportKey.startsWith('consolidation.') ? 'Grup konsolidasyon raporu' : 'Rapor')}</Td><Td>{event.format.toUpperCase()}</Td><Td>{event.rowCount}</Td></Tr>)}</tbody></Table></TableWrap>}
  </Card>;
}
