import { z } from 'zod';
import {
  accountLedgerQuerySchema,
  agingQuerySchema,
  attendanceLaborQuerySchema,
  attendanceMonthQuerySchema,
  payrollCostQuerySchema,
  premiumSummaryQuerySchema,
  foreignDocListQuerySchema,
  chequeListQuerySchema,
  chequeMaturityQuerySchema,
  chequeDueQuerySchema,
  chequeBouncedQuerySchema,
  bankGuaranteeListQuerySchema,
  listSalesDocsQuerySchema,
  listSerialsQuerySchema,
  listImportFilesQuerySchema,
  listExpenseEntriesQuerySchema,
  expenseReportQuerySchema,
  listDeliveryNotesQuerySchema,
  guaranteeListQuerySchema,
  fullDataQuerySchema,
  fxDifferencesQuerySchema,
  generalLedgerQuerySchema,
  isoDate,
  itemMovementsQuerySchema,
  itemProfitQuerySchema,
  journalBookQuerySchema,
  openItemsQuerySchema,
  partyStatementQuerySchema,
  salesReportQuerySchema,
  stockStatusQuerySchema,
  todayIso,
  trialBalanceQuerySchema,
  treasuryStatementQuerySchema,
  uuid,
  vatSummaryQuerySchema,
  type ExportFormat,
  type Permission,
} from '@erp/shared';
import type { ReportTable } from '../../files/table';
import {
  accountLedgerTable,
  bankReconciliationTable,
  fxDifferencesTable,
  generalLedgerTable,
  itemCardTable,
  itemProfitTable,
  journalBookTable,
  partyAgingTable,
  partyOpenItemsTable,
  partyStatementTable,
  projectCostByCodeTable,
  projectCostReportTable,
  progressPaymentsTable,
  variationOrderTable,
  employeesTable,
  attendanceSummaryTable,
  attendanceLaborTable,
  payrollRegisterTable,
  payrollCostTable,
  socialDeclarationTable,
  socialPremiumSummaryTable,
  foreignDocsTable,
  chequesTable,
  chequeMaturityTable,
  chequesDueTable,
  chequesBouncedTable,
  bankGuaranteesTable,
  salesDocsTable,
  serialsTable,
  importFilesTable,
  importFileReportTable,
  importLandedItemsTable,
  expenseEntriesTable,
  expenseReportTables,
  priceListItemsTable,
  partyPricesTable,
  deliveryNotesTable,
  foreignGuaranteesTable,
  variationOrdersTable,
  subcontractRegisterTable,
  projectsSummaryTable,
  cashForecastTable,
  projectProfitabilityTable,
  overdueInstallmentsTable,
  realEstateUnitsTable,
  salesContractsTable,
  salesScheduleTable,
  salesReportTable,
  stockStatusTable,
  trialBalanceTable,
  treasuryStatementTable,
  vatSummaryTable,
  type BuildCtx,
} from './builders';
import { fullDataTables } from './full-data';

/** Dışa aktarılabilir rapor: kendi modül ve izniyle korunur (ekran raporuyla aynı). */
export interface ExportDef {
  key: string;
  module: string;
  permission: Permission;
  schema: z.ZodType<Record<string, unknown>>;
  build: (ctx: BuildCtx, q: never) => Promise<ReportTable[]>;
  formats: readonly ExportFormat[];
  /** Dosya adı (uzantısız, ASCII): rapor + dönem/tarih. */
  fileName: (q: never) => string;
}

function def<S extends z.ZodType<Record<string, unknown>>>(
  d: Omit<ExportDef, 'schema' | 'build' | 'fileName' | 'formats'> & {
    schema: S;
    build: (ctx: BuildCtx, q: z.infer<S>) => Promise<ReportTable[]>;
    file: string | ((q: z.infer<S>) => string);
    formats?: readonly ExportFormat[];
  },
): ExportDef {
  return {
    key: d.key,
    module: d.module,
    permission: d.permission,
    schema: d.schema,
    build: d.build as ExportDef['build'],
    formats: d.formats ?? ['xlsx', 'csv'],
    fileName: ((q: z.infer<S>) => (typeof d.file === 'function' ? d.file(q) : d.file)) as ExportDef['fileName'],
  };
}

const range = (name: string) => (q: { from: string; to: string }) => `${name}-${q.from}_${q.to}`;
const asOf = (name: string) => (q: { asOf: string }) => `${name}-${q.asOf}`;

const ledger = { module: 'core.ledger', permission: 'reports.read' } as const;
const invoices = { module: 'core.invoices', permission: 'reports.read' } as const;

export const EXPORTS: readonly ExportDef[] = [
  // Mevcut raporlar
  def({ key: 'trial-balance', ...ledger, schema: trialBalanceQuerySchema.extend({ view: z.enum(['groups', 'accounts']).default('groups') }), build: trialBalanceTable, file: range('mizan') }),
  def({ key: 'account-ledger', ...ledger, schema: accountLedgerQuerySchema, build: accountLedgerTable, file: range('muavin') }),
  def({ key: 'party-aging', module: 'core.parties', permission: 'parties.read', schema: agingQuerySchema, build: partyAgingTable, file: (q) => `yaslandirma-${q.type === 'receivable' ? 'alacak' : 'borc'}-${q.asOf}` }),
  def({ key: 'party-statement', module: 'core.parties', permission: 'parties.read', schema: partyStatementQuerySchema.extend({ partyId: uuid }), build: partyStatementTable, file: range('cari-ekstre') }),
  def({ key: 'party-open-items', module: 'core.parties', permission: 'parties.read', schema: openItemsQuerySchema.extend({ partyId: uuid }), build: partyOpenItemsTable, file: asOf('acik-kalemler') }),
  def({ key: 'stock-status', module: 'core.inventory', permission: 'inventory.read', schema: stockStatusQuerySchema, build: stockStatusTable, file: asOf('stok-durumu') }),
  def({ key: 'item-card', module: 'core.inventory', permission: 'inventory.read', schema: itemMovementsQuerySchema.extend({ itemId: uuid }), build: itemCardTable, file: range('stok-karti') }),
  def({ key: 'vat-summary', ...invoices, schema: vatSummaryQuerySchema, build: vatSummaryTable, file: range('kdv-ozeti') }),
  def({ key: 'treasury-statement', module: 'core.treasury', permission: 'treasury.read', schema: treasuryStatementQuerySchema.extend({ accountId: uuid }), build: treasuryStatementTable, file: range('hesap-ekstresi') }),
  // Yeni raporlar
  def({ key: 'journal-book', ...ledger, schema: journalBookQuerySchema.pick({ from: true, to: true }), build: journalBookTable, file: range('yevmiye-defteri') }),
  def({ key: 'general-ledger', ...ledger, schema: generalLedgerQuerySchema.pick({ from: true, to: true, codePrefix: true }), build: generalLedgerTable, file: range('kebir') }),
  def({ key: 'sales-report', ...invoices, schema: salesReportQuerySchema, build: (ctx, q) => salesReportTable(ctx, 'sales', q), file: (q) => `satis-raporu-${q.groupBy}-${q.from}_${q.to}` }),
  def({ key: 'purchase-report', ...invoices, schema: salesReportQuerySchema, build: (ctx, q) => salesReportTable(ctx, 'purchases', q), file: (q) => `alis-raporu-${q.groupBy}-${q.from}_${q.to}` }),
  def({ key: 'item-profitability', ...invoices, schema: itemProfitQuerySchema, build: itemProfitTable, file: range('stok-karliligi') }),
  def({ key: 'fx-differences', module: 'core.treasury', permission: 'reports.read', schema: fxDifferencesQuerySchema, build: fxDifferencesTable, file: range('kambiyo-raporu') }),
  def({
    key: 'bank-reconciliation',
    module: 'core.treasury',
    permission: 'treasury.read',
    schema: z.object({ accountId: uuid, from: isoDate.optional(), to: isoDate.optional() }),
    build: bankReconciliationTable,
    file: (q) => `banka-mutabakati-${q.from ?? 'baslangic'}_${q.to ?? todayIso()}`,
  }),
  def({
    key: 'project-cost-report',
    module: 'construction.projects',
    permission: 'projects.read',
    schema: z.object({ projectId: uuid, asOf: isoDate }),
    build: projectCostReportTable,
    file: (q) => `proje-maliyet-${q.asOf}`,
  }),
  def({
    key: 'project-cost-by-code',
    module: 'construction.projects',
    permission: 'projects.read',
    schema: z.object({ projectId: uuid, asOf: isoDate }),
    build: projectCostByCodeTable,
    file: (q) => `proje-maliyet-kodu-${q.asOf}`,
  }),
  def({
    key: 'subcontract-register',
    module: 'construction.subcontracts',
    permission: 'subcontracts.read',
    schema: z.object({ projectId: uuid.optional(), direction: z.enum(['payable', 'receivable']).optional() }),
    build: subcontractRegisterTable,
    file: () => `tasaron-sozlesmeleri-${todayIso()}`,
  }),
  def({
    key: 'project-profitability',
    module: 'construction.projects',
    permission: 'projects.read',
    schema: z.object({ asOf: isoDate.optional() }),
    build: projectProfitabilityTable,
    file: (q: { asOf?: string }) => `proje-karliligi-${q.asOf ?? todayIso()}`,
  }),
  def({
    key: 'cash-forecast',
    module: 'core.treasury',
    permission: 'treasury.read',
    schema: z.object({ from: isoDate.optional(), weeks: z.coerce.number().int().min(4).max(26).optional() }),
    build: cashForecastTable,
    file: () => `nakit-projeksiyonu-${todayIso()}`,
  }),
  def({
    key: 'real-estate-units',
    module: 'construction.realestate',
    permission: 'realestate.read',
    schema: z.object({ projectId: uuid.optional(), status: z.string().optional() }),
    build: realEstateUnitsTable,
    file: () => `birim-envanteri-${todayIso()}`,
  }),
  def({
    key: 'sales-contracts',
    module: 'construction.realestate',
    permission: 'realestate.read',
    schema: z.object({ projectId: uuid.optional(), status: z.string().optional() }),
    build: salesContractsTable,
    file: () => `satis-sozlesmeleri-${todayIso()}`,
  }),
  def({
    key: 'sales-schedule',
    module: 'construction.realestate',
    permission: 'realestate.read',
    schema: z.object({ contractId: uuid }),
    build: salesScheduleTable,
    file: () => `odeme-plani-${todayIso()}`,
  }),
  def({
    key: 'overdue-installments',
    module: 'construction.realestate',
    permission: 'realestate.read',
    schema: z.object({ projectId: uuid.optional(), asOf: isoDate.optional(), overdue: z.enum(['true', 'false']).transform((v) => v === 'true').optional() }),
    build: overdueInstallmentsTable,
    file: () => `taksitler-${todayIso()}`,
  }),
  def({
    key: 'progress-payments',
    module: 'construction.subcontracts',
    permission: 'subcontracts.read',
    schema: z.object({ projectId: uuid.optional(), subcontractId: uuid.optional(), direction: z.enum(['payable', 'receivable']).optional() }),
    build: progressPaymentsTable,
    file: () => `hakedisler-${todayIso()}`,
  }),
  def({
    key: 'employees',
    module: 'hr.core',
    permission: 'hr.read',
    schema: z.object({ status: z.enum(['active', 'left']).optional() }),
    build: employeesTable,
    file: () => `personel-${todayIso()}`,
    formats: ['xlsx', 'csv'],
  }),
  def({
    key: 'attendance-summary',
    module: 'hr.core',
    permission: 'hr.read',
    schema: attendanceMonthQuerySchema,
    build: attendanceSummaryTable,
    file: (q) => `puantaj-ozeti-${q.month}`,
  }),
  def({
    key: 'attendance-labor',
    module: 'hr.core',
    permission: 'hr.read',
    schema: attendanceLaborQuerySchema,
    build: attendanceLaborTable,
    file: range('iscilik-saatleri'),
  }),
  def({
    key: 'payroll-register',
    module: 'hr.payroll',
    permission: 'hr.payroll',
    schema: z.object({ id: uuid }),
    build: payrollRegisterTable,
    file: () => `bordro-kaydi-${todayIso()}`,
  }),
  def({
    key: 'payroll-cost',
    module: 'hr.payroll',
    permission: 'hr.payroll',
    schema: payrollCostQuerySchema,
    build: payrollCostTable,
    file: (q) => `bordro-maliyeti-${q.from}_${q.to}`,
  }),
  def({
    key: 'social-declaration',
    module: 'hr.socialsecurity',
    permission: 'hr.payroll',
    schema: z.object({ id: uuid }),
    build: socialDeclarationTable,
    file: () => `sosyal-guvenlik-bildirimi-${todayIso()}`,
  }),
  def({
    key: 'social-premium-summary',
    module: 'hr.socialsecurity',
    permission: 'hr.payroll',
    schema: premiumSummaryQuerySchema,
    build: socialPremiumSummaryTable,
    file: (q) => `sosyal-guvenlik-prim-ozeti-${q.from}_${q.to}`,
  }),
  def({ key: 'cheques', module: 'treasury.cheques', permission: 'treasury.read', schema: chequeListQuerySchema, build: chequesTable, file: () => `cek-senet-portfoyu-${todayIso()}` }),
  def({ key: 'cheque-maturity', module: 'treasury.cheques', permission: 'treasury.read', schema: chequeMaturityQuerySchema, build: chequeMaturityTable, file: (q) => `cek-senet-vade-analizi-${q.asOf ?? todayIso()}` }),
  def({ key: 'cheques-due', module: 'treasury.cheques', permission: 'treasury.read', schema: chequeDueQuerySchema, build: chequesDueTable, file: () => `vadesi-gelen-cek-senet-${todayIso()}` }),
  def({ key: 'cheques-bounced', module: 'treasury.cheques', permission: 'treasury.read', schema: chequeBouncedQuerySchema, build: chequesBouncedTable, file: () => `karsiliksiz-cek-senet-${todayIso()}` }),
  def({ key: 'sales-docs', module: 'invoices.orders', permission: 'invoices.read', schema: listSalesDocsQuerySchema.omit({ limit: true, offset: true }), build: salesDocsTable, file: () => `satis-teklif-siparis-${todayIso()}` }),
  def({ key: 'import-files', module: 'inventory.imports', permission: 'inventory.read', schema: listImportFilesQuerySchema.omit({ limit: true, offset: true }), build: importFilesTable, file: () => `ithalat-dosyalari-${todayIso()}` }),
  def({ key: 'import-file-report', module: 'inventory.imports', permission: 'inventory.read', schema: z.object({ id: uuid }), build: importFileReportTable, file: () => `ithalat-maliyet-${todayIso()}` }),
  def({ key: 'import-landed-items', module: 'inventory.imports', permission: 'inventory.read', schema: z.object({ from: isoDate.optional(), to: isoDate.optional(), itemId: uuid.optional() }), build: importLandedItemsTable, file: () => `ithalat-maliyeti-kart-bazinda-${todayIso()}` }),
  def({ key: 'expense-entries', module: 'treasury.expenses', permission: 'treasury.read', schema: listExpenseEntriesQuerySchema.omit({ limit: true, offset: true }), build: expenseEntriesTable, file: () => `gider-fisleri-${todayIso()}` }),
  def({ key: 'expense-report', module: 'treasury.expenses', permission: 'treasury.read', schema: expenseReportQuerySchema, build: expenseReportTables, file: (q) => `gider-raporu-${q.from}-${q.to}` }),
  def({ key: 'serials', module: 'inventory.serials', permission: 'inventory.read', schema: listSerialsQuerySchema.omit({ limit: true, offset: true }), build: serialsTable, file: () => `seri-no-listesi-${todayIso()}` }),
  def({ key: 'price-list-items', module: 'sales.pricelists', permission: 'invoices.read', schema: z.object({ listId: uuid }), build: priceListItemsTable, file: () => `fiyat-listesi-${todayIso()}` }),
  def({ key: 'party-prices', module: 'sales.pricelists', permission: 'invoices.read', schema: z.object({ partyId: uuid.optional() }), build: partyPricesTable, file: () => `cari-ozel-fiyat-${todayIso()}` }),
  def({ key: 'delivery-notes', module: 'core.invoices', permission: 'deliveries.read', schema: listDeliveryNotesQuerySchema.omit({ limit: true, offset: true }), build: deliveryNotesTable, file: () => `irsaliyeler-${todayIso()}` }),
  def({ key: 'bank-guarantees', module: 'treasury.guarantees', permission: 'treasury.read', schema: bankGuaranteeListQuerySchema, build: bankGuaranteesTable, file: () => `banka-teminat-mektuplari-${todayIso()}` }),
  def({
    key: 'foreign-documents',
    module: 'hr.foreign',
    permission: 'hr.read',
    schema: foreignDocListQuerySchema,
    build: foreignDocsTable,
    file: () => `yabanci-isci-belgeleri-${todayIso()}`,
  }),
  def({
    key: 'foreign-guarantees',
    module: 'hr.foreign',
    permission: 'hr.read',
    schema: guaranteeListQuerySchema,
    build: foreignGuaranteesTable,
    file: () => `yabanci-isci-teminatlari-${todayIso()}`,
  }),
  def({
    key: 'variation-orders',
    module: 'construction.subcontracts',
    permission: 'subcontracts.read',
    schema: z.object({
      projectId: uuid.optional(),
      subcontractId: uuid.optional(),
      direction: z.enum(['payable', 'receivable']).optional(),
      status: z.string().optional(),
    }),
    build: variationOrdersTable,
    file: () => `degisiklik-emirleri-${todayIso()}`,
  }),
  def({
    key: 'variation-order',
    module: 'construction.subcontracts',
    permission: 'subcontracts.read',
    schema: z.object({ id: uuid }),
    build: variationOrderTable,
    file: () => `degisiklik-emri-${todayIso()}`,
  }),
  def({ key: 'projects-summary', module: 'construction.projects', permission: 'projects.read', schema: z.object({ asOf: isoDate }), build: projectsSummaryTable, file: asOf('proje-ozeti') }),
  def({ key: 'full-data', module: 'core.settings', permission: 'data.export', schema: fullDataQuerySchema, build: fullDataTables, file: () => `tum-veriler-${todayIso()}`, formats: ['xlsx'] }),
];

export const EXPORT_BY_KEY = new Map(EXPORTS.map((e) => [e.key, e]));
