import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Plus,Tag,Pencil,History } from 'lucide-react';
import { campaignSchema,todayIso,type Campaign,type CampaignRow,type CampaignPreview,type SearchHit } from '@erp/shared';
import { PageHeader,Card,CardHeader } from '../../components/ui/Card';
import { Button } from '../../components/ui/Button';
import { Badge } from '../../components/ui/Badge';
import { Field,Input,Select,Textarea } from '../../components/ui/Field';
import { Sheet } from '../../components/ui/Sheet';
import { MoneyInput } from '../../components/ui/MoneyInput';
import { CurrencyOptions } from '../../components/ui/CurrencyOptions';
import { Callout,PageLoading,EmptyState } from '../../components/ui/Feedback';
import { useToast } from '../../components/ui/Toast';
import { useCQuery,useCMutation,useCan } from '../../lib/queries';
import { useCompany } from '../../lib/session';
import { moneyIn,formatDateTR } from '../../lib/format';
import { errorMessage } from '../../lib/errors';
import { RecordPicker } from '../workspace/RecordPicker';
const invalidate=[['campaigns'],['invoices'],['invoice']];
export function CampaignsPage(){return <CampaignsContent key={useCompany().id} />;}
function CampaignsContent(){
  const can=useCan(),query=useCQuery<{items:CampaignRow[]}>(['campaigns'],'/api/sales/campaigns');
  const [edit,setEdit]=useState<CampaignRow|'new'|null>(null),[selected,setSelected]=useState<{row:CampaignRow;history:boolean}|null>(null),today=todayIso();
  return <><PageHeader title="Kampanya ve promosyon" description="Dönem, müşteri, ürün ve miktar koşullarına göre satış indirimleri hazırlayın." actions={can('invoices.manage')&&<Button variant="primary" onClick={()=>setEdit('new')}><Plus className="size-4" />Yeni kampanya</Button>} />
    {query.error?<Callout tone="danger">{errorMessage(query.error)}</Callout>:query.isPending?<PageLoading />:!query.data?.items.length?<Card><EmptyState icon={<Tag className="size-5" />} title="İlk kampanyanızı hazırlayın" description="İndirimi faturada önizleyin; tutarlar mevcut fatura hesaplarıyla güncellenir." /></Card>:<div className="grid items-start gap-5 xl:grid-cols-2">{query.data.items.map(row=><Card key={row.id} className="min-w-0 overflow-hidden"><CardHeader title={row.title} description={`${row.code} · ${formatDateTR(row.from)} — ${formatDateTR(row.to)}`} action={<Badge tone={!row.active?'neutral':row.to<today?'danger':row.from>today?'warning':'success'}>{!row.active?'Pasif':row.to<today?'Sona erdi':row.from>today?'Yaklaşan':'Aktif'}</Badge>} /><div className="space-y-4 p-5"><div className="flex flex-wrap justify-between gap-3"><p className="text-3xl tabular-nums">%{row.discountPct}<span className="ml-2 text-sm text-muted">indirim</span></p><p className="text-sm text-muted">{row.applications} uygulama</p></div>{row.description&&<p className="break-words text-sm text-muted">{row.description}</p>}<dl className="grid grid-cols-2 gap-3 text-xs"><div><dt className="text-muted">Asgari tutar</dt><dd className="mt-1">{moneyIn(row.minimumAmount,row.currency)}</dd></div><div><dt className="text-muted">Satırdaki asgari miktar</dt><dd className="mt-1">{row.minimumQuantity}</dd></div><div><dt className="text-muted">Müşteri kapsamı</dt><dd className="mt-1">{row.partyId?'Seçili müşteri':'Tüm müşteriler'}</dd></div><div><dt className="text-muted">Ürün kapsamı</dt><dd className="mt-1">{row.itemId?'Seçili ürün / hizmet':'Tüm satırlar'}</dd></div></dl><div className="flex flex-wrap gap-1">{can('invoices.manage')&&<><Button size="sm" onClick={()=>setSelected({row,history:false})}>Faturada önizle</Button><Button size="sm" variant="ghost" onClick={()=>setEdit(row)}><Pencil className="size-3.5" />Düzenle</Button></>}<Button size="sm" variant="ghost" onClick={()=>setSelected({row,history:true})}><History className="size-3.5" />Geçmiş</Button></div></div></Card>)}</div>}
    {edit&&<CampaignEditor row={edit==='new'?null:edit} onClose={()=>setEdit(null)} />}{selected&&(selected.history?<CampaignHistory row={selected.row} onClose={()=>setSelected(null)} />:<CampaignApply row={selected.row} onClose={()=>setSelected(null)} />)}</>;
}
function CampaignEditor({row,onClose}:{row:CampaignRow|null;onClose:()=>void}){
  const company=useCompany(),toast=useToast(),can=useCan(),today=todayIso();
  const [value,setValue]=useState<Campaign>(row??{code:'',title:'',description:'',from:today,to:today,currency:company.baseCurrency as Campaign['currency'],discountPct:'10',minimumAmount:'0',minimumQuantity:'1',partyId:null,itemId:null,active:true});
  const [error,setError]=useState(''),[party,setParty]=useState<SearchHit|null>(null);
  const items=useCQuery<{items:{id:string;code:string;name:string}[]}>(['items'],'/api/items',{enabled:can('inventory.read')});
  const change=<K extends keyof Campaign>(key:K,v:Campaign[K])=>setValue(s=>({...s,[key]:v}));
  const save=useCMutation((input:Campaign,call)=>call(row?`/api/sales/campaigns/${row.id}`:'/api/sales/campaigns',{method:row?'PUT':'POST',body:row?{config:input,version:row.version}:input}),invalidate);
  function submit(){const parsed=campaignSchema.safeParse(value);if(!parsed.success){setError(parsed.error.issues[0]?.message??'Alanları kontrol edin.');return;}setError('');save.mutate(parsed.data,{onSuccess:()=>{toast.success('Kampanya kaydedildi.');onClose();}});}
  return <Sheet open onOpenChange={o=>{if(!o)onClose();}} title={row?'Kampanyayı düzenle':'Yeni kampanya'} footer={<Button variant="primary" loading={save.isPending} onClick={submit}>Kampanyayı kaydet</Button>}><div className="space-y-5">
    {(error||save.error)&&<Callout tone="danger">{error||errorMessage(save.error)}</Callout>}
    <div className="grid gap-4 sm:grid-cols-2"><Field label="Kampanya kodu" required>{id=><Input id={id} value={value.code} maxLength={40} onChange={e=>change('code',e.target.value)} />}</Field><Field label="Kampanya adı" required>{id=><Input id={id} value={value.title} maxLength={150} onChange={e=>change('title',e.target.value)} />}</Field><Field label="Başlangıç">{id=><Input id={id} type="date" value={value.from} onChange={e=>change('from',e.target.value)} />}</Field><Field label="Bitiş">{id=><Input id={id} type="date" value={value.to} min={value.from} onChange={e=>change('to',e.target.value)} />}</Field><Field label="Para birimi">{id=><Select id={id} value={value.currency} onChange={e=>change('currency',e.target.value as Campaign['currency'])}><CurrencyOptions /></Select>}</Field><Field label="İndirim (%)">{id=><MoneyInput id={id} value={value.discountPct} decimals={4} onChange={v=>change('discountPct',v)} />}</Field><Field label="Asgari fiyat toplamı" hint="Kapsamdaki satırların indirimsiz miktar × fiyat toplamı; fatura KDV dahil ise bu tutar da dahildir.">{id=><MoneyInput id={id} value={value.minimumAmount} onChange={v=>change('minimumAmount',v)} />}</Field><Field label="Satırdaki asgari miktar">{id=><MoneyInput id={id} value={value.minimumQuantity} decimals={4} onChange={v=>change('minimumQuantity',v)} />}</Field></div>
    {can('parties.read')&&<><RecordPicker kind="party" value={party} label="Müşteri (boşsa tümü)" onChange={v=>{setParty(v);change('partyId',v?.id??null);}} />{value.partyId&&!party&&<p className="break-all text-xs text-muted">Mevcut müşteri: {value.partyId}<Button size="sm" variant="ghost" onClick={()=>change('partyId',null)}>Tüm müşteriler</Button></p>}</>}
    {can('inventory.read')&&<Field label="Ürün / hizmet kapsamı">{id=><Select id={id} value={value.itemId??''} onChange={e=>change('itemId',e.target.value||null)}><option value="">Tüm satırlar</option>{value.itemId&&!items.data?.items.some(i=>i.id===value.itemId)&&<option value={value.itemId}>Mevcut seçim</option>}{items.data?.items.map(i=><option key={i.id} value={i.id}>{i.code} · {i.name}</option>)}</Select>}</Field>}
    <Field label="Açıklama">{id=><Textarea id={id} value={value.description} maxLength={1000} onChange={e=>change('description',e.target.value)} />}</Field><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={value.active} onChange={e=>change('active',e.target.checked)} />Kampanya aktif</label><p className="text-xs text-muted">Önceki uygulamaların fiyatları ve kampanya koşulları korunur. Bir faturaya tek kampanya uygulanır.</p>
  </div></Sheet>;
}
function CampaignApply({row,onClose}:{row:CampaignRow;onClose:()=>void}){
  const [invoice,setInvoice]=useState<SearchHit|null>(null),[done,setDone]=useState(false),toast=useToast();
  const preview=useCMutation((invoiceId:string,call)=>call<CampaignPreview>(`/api/sales/campaigns/${row.id}/preview`,{method:'POST',body:{invoiceId}}));
  const apply=useCMutation((input:{invoiceId:string;fingerprint:string},call)=>call(`/api/sales/campaigns/${row.id}/apply`,{method:'POST',body:input}),invalidate);
  const data=preview.variables===invoice?.id?preview.data:undefined;
  return <Sheet open onOpenChange={o=>{if(!o)onClose();}} title={row.title} description="Kaydedilmiş satış taslağını seçin; uygulamadan önce yeni toplamı görün." footer={!done&&<><Button disabled={!invoice} loading={preview.isPending} onClick={()=>preview.mutate(invoice!.id)}>İndirimi önizle</Button><Button variant="primary" disabled={!data?.eligible} loading={apply.isPending} onClick={()=>apply.mutate({invoiceId:invoice!.id,fingerprint:data!.fingerprint},{onSuccess:()=>{setDone(true);toast.success('Kampanya fatura taslağına uygulandı.');}})}>Taslağa uygula</Button></>}><div className="space-y-5">
    {(preview.error||apply.error)&&<Callout tone="danger">{errorMessage(preview.error??apply.error)}</Callout>}{done?<><Callout>İndirim kaydedildi. Faturayı inceleyip onay ve muhasebeleştirme adımlarıyla devam edin.</Callout><Link className="link text-sm" to={`/invoices/${invoice!.id}`}>Faturayı aç</Link></>:<RecordPicker kind="invoice" value={invoice} label="Satış faturası taslağı" onChange={setInvoice} />}
    {data&&<><dl className="grid grid-cols-2 overflow-hidden rounded-xl border border-border"><div className="p-4"><dt className="text-xs text-muted">Önceki genel toplam</dt><dd className="mt-2 tabular-nums">{moneyIn(data.grossBefore,data.currency)}</dd></div><div className="border-l border-border p-4"><dt className="text-xs text-muted">Kampanyalı genel toplam</dt><dd className="mt-2 tabular-nums">{moneyIn(data.grossAfter,data.currency)}</dd></div></dl>{data.reasons.map(reason=><Callout key={reason} tone="warning">{reason}</Callout>)}<ul className="divide-y divide-border">{data.lines.map(l=><li key={l.lineNo} className="flex justify-between gap-4 py-3 text-sm"><span className="min-w-0 break-words">{l.description}<span className="mt-1 block text-xs text-muted">{l.eligible?'Kapsamda':'Kapsam dışında'}</span></span><span className="shrink-0">%{l.discountPct}</span></li>)}</ul><p className="text-xs text-muted">Net indirim: {moneyIn(data.discountNet,data.currency)}. Muhasebe kaydı fatura onayında oluşur.</p></>}
  </div></Sheet>;
}
function CampaignHistory({row,onClose}:{row:CampaignRow;onClose:()=>void}){
  const query=useCQuery<{items:{id:string;invoiceId:string;invoiceNo:string|null;status:string;createdAt:string;userName:string;snapshot:CampaignPreview}[]}>(['campaigns',row.id,'history'],`/api/sales/campaigns/${row.id}/history`);
  return <Sheet open onOpenChange={o=>{if(!o)onClose();}} title={`${row.title} · geçmiş`} description="Son 200 uygulama; tarihli kampanya koşulları değişmeden saklanır.">{query.error?<Callout tone="danger">{errorMessage(query.error)}</Callout>:!query.data?<PageLoading />:!query.data.items.length?<p className="text-sm text-muted">Henüz uygulanmış fatura yok.</p>:<ul className="divide-y divide-border">{query.data.items.map(a=><li key={a.id} className="space-y-2 py-4"><Link className="link text-sm" to={`/invoices/${a.invoiceId}`}>{a.invoiceNo??'Fatura taslağı'}</Link><p className="text-xs text-muted">{a.userName} · {new Date(a.createdAt).toLocaleString('tr-TR')} · %{a.snapshot.campaign.discountPct}</p><p className="text-sm">{moneyIn(a.snapshot.grossBefore,a.snapshot.currency)} → {moneyIn(a.snapshot.grossAfter,a.snapshot.currency)}</p><p className="text-xs text-muted">{a.status==='draft'?'Taslak':a.status==='posted'?'Muhasebeleştirildi':'İptal edildi'}</p></li>)}</ul>}</Sheet>;
}
