import { useState } from 'react';
import { Activity, Clock3, Download, Printer, ArrowRight, UsersRound, CheckCircle2 } from 'lucide-react';
import { todayIso, type ActivityReport, type ActivityEvent } from '@erp/shared';
import { Link } from 'react-router-dom';
import { useCompany } from '../../lib/session';
import { useCQuery } from '../../lib/queries';
import { Card, CardHeader, PageHeader } from '../../components/ui/Card';
import { Input, Select } from '../../components/ui/Field';
import { Button } from '../../components/ui/Button';
import { Badge } from '../../components/ui/Badge';
import { Table, TableWrap, Th, Td, Tr } from '../../components/ui/Table';
import { Sheet } from '../../components/ui/Sheet';
import { Callout, EmptyState, PageLoading } from '../../components/ui/Feedback';
import { saveBlob } from '../../lib/download';
import { formatDateTR } from '../../lib/format';
import { duration } from '../workspace/TimeTracking';

const tableLabels:Record<string,string>={work_items:'Görevler',work_time_sessions:'Çalışma süreleri',record_documents:'Belge arşivi',company_operations_settings:'İşletim ayarları',administration_runs:'Otomatik işler',exchange_rates:'Döviz kurları',journal_entries:'Yevmiye fişleri',journal_lines:'Yevmiye satırları',accounts:'Hesap planı',invoices:'Faturalar',invoice_lines:'Fatura satırları',items:'Stok kartları',warehouses:'Depolar',stock_movements:'Stok hareketleri',stock_lines:'Stok satırları',parties:'Cariler',party_contacts:'Cari iletişim',treasury_transactions:'Kasa / banka hareketleri',treasury_accounts:'Kasa / banka hesapları',bank_statements:'Banka ekstreleri',projects:'Projeler',project_wbs:'İş kalemleri',project_budgets:'Proje bütçeleri',construction_drawings:'Çizim revizyonları',construction_pins:'Plandaki sorunlar',construction_photos:'Saha fotoğrafları',construction_locations:'Mahaller',construction_assets:'Saha dosyaları',construction_jobs:'OCR / BIM işlemleri',construction_snapshots:'Maliyet tahminleri',construction_model_links:'Model bağlantıları',subcontracts:'Taşeron sözleşmeleri',progress_payments:'Hakedişler',progress_payment_lines:'Hakediş satırları',variation_orders:'Değişiklik emirleri',approval_requests:'Onay talepleri',approval_decisions:'Onay kararları',purchase_requests:'Satın alma talepleri',purchase_request_lines:'Talep satırları',purchase_orders:'Satın alma siparişleri',purchase_order_lines:'Sipariş satırları',units:'Bağımsız birimler',sales_contracts:'Satış sözleşmeleri',sales_installments:'Taksitler',employees:'Personel',attendance_entries:'Puantaj kayıtları',attendance_months:'Puantaj ayları',foreign_worker_docs:'Yabancı işçi belgeleri',foreign_doc_renewals:'Belge yenilemeleri'};
const fieldLabels:Record<string,string>={title:'Başlık',name:'Ad',code:'Kod',full_name:'Ad soyad',description:'Açıklama',status:'Durum',priority:'Öncelik',due_date:'Vade',owner_id:'Sorumlu',version:'Sürüm',doc_no:'Belge no',invoice_no:'Fatura no',txn_no:'Hareket no',entry_no:'Fiş no',event_date:'Olay tarihi',work_date:'Çalışma günü',normal_hours:'Normal saat',overtime_hours:'Fazla mesai',amount:'Tutar',currency_code:'Para birimi',quantity:'Miktar',total:'Toplam',net_total:'Net toplam',gross_total:'Genel toplam',expiry_date:'Bitiş tarihi',filename:'Dosya adı',size:'Dosya boyutu',updated_at:'Güncelleme',created_at:'Oluşturma',started_at:'Başlangıç',stopped_at:'Bitiş',note:'Not'};
const actionLabels:Record<string,string>={INSERT:'Oluşturuldu',UPDATE:'Değiştirildi',DELETE:'Silindi',insert:'Oluşturuldu',update:'Değiştirildi',delete:'Silindi'};
Object.assign(tableLabels,{operation_entries:'Saha kayıtları',construction_workflows:'Proje süreçleri',stock_documents:'Stok belgeleri',real_estate_units:'Bağımsız birimler',approval_steps:'Onay adımları',cheques:'Çek / senetler',cheque_events:'Çek işlemleri',cheque_batches:'Çek toplu işlemleri',cheque_allocations:'Çek dağıtımları',agenda_items:'Ajanda',recurring_templates:'Tekrar planları',saved_insights:'Kaydedilmiş raporlar'});
Object.assign(fieldLabels,{payload:'İşlem ayrıntıları',settings:'İşletim ayarları',config:'Rapor ayarları',amount_base:'Defter tutarı',total_base:'Defter toplamı',fx_rate:'Döviz kuru',recurrence:'Tekrar kuralı',next_date:'Sonraki tarih',generated:'Oluşturulan kayıt',all_day:'Tüm gün',remind_before_minutes:'Hatırlatma (dakika)',start_time:'Başlangıç saati',end_time:'Bitiş saati',archived:'Arşiv durumu',error:'Hata'});
const detailValue=(value:unknown)=>value==null?'—':typeof value==='object'?JSON.stringify(value,null,2):typeof value==='boolean'?(value?'Evet':'Hayır'):String(value);
Object.assign(tableLabels,{sales_campaigns:'Satış kampanyaları',campaign_applications:'Kampanya uygulamaları',company_budgets:'Şirket ve departman bütçeleri',fixed_assets:'Demirbaş kartları',asset_depreciation:'Amortisman dönemleri',expense_cards:'Gider kartları',expense_entries:'Gider fişleri',employee_advances:'Personel avansları',employee_advance_settlements:'Avans kapama hareketleri',employee_advance_events:'Avans durum geçmişi'});
Object.assign(fieldLabels,{revision:'Revizyon',series_id:'Bütçe serisi',approved_by:'Onaylayan',approved_at:'Onay zamanı',snapshot:'Tarihli hesaplama kaydı',advance_applied_amount:'Mahsup edilen avans',employee_id:'Personel',advance_id:'Avans',payment_kind:'Ödeme şekli',cancel_reason:'İptal gerekçesi',reversed_at:'Geri alma zamanı',reverse_reason:'Geri alma gerekçesi',settled_date:'Mahsup tarihi',expense_entry_id:'Gider fişi',settled_amount:'Kapanan avans',advance_date:'Avans tarihi'});
const when=(v:string)=>new Intl.DateTimeFormat('tr-TR',{dateStyle:'short',timeStyle:'medium',timeZone:'Europe/Nicosia'}).format(new Date(v));
function source(event:ActivityEvent) {
  if(event.table==='company_budgets'&&event.rowId)return '/accounting/budgets?budget='+encodeURIComponent(event.rowId);
  if(event.table==='fixed_assets'&&event.rowId)return '/accounting/fixed-assets?asset='+encodeURIComponent(event.rowId);
  if(event.table==='asset_depreciation')return '/accounting/fixed-assets';
  if(event.table==='expense_entries'&&event.rowId)return '/treasury/expenses';
  const prefix:Record<string,string>={invoices:'/invoices/',parties:'/parties/',projects:'/projects/',subcontracts:'/subcontracts/',progress_payments:'/progress-payments/',variation_orders:'/variation-orders/',purchase_requests:'/purchasing/requests/',purchase_orders:'/purchasing/orders/',sales_contracts:'/real-estate/contracts/',employees:'/hr/employees/'};
  return prefix[event.table] && event.rowId && event.action.toUpperCase()!=='DELETE' ? prefix[event.table]+event.rowId : null;
}
export function ActivityPage() {return <ActivityContent key={useCompany().id} />;}
function ActivityContent() {
  const company=useCompany();
  const [from,setFrom]=useState(todayIso().slice(0,8)+'01'),[to,setTo]=useState(todayIso());
  const [userId,setUserId]=useState(''),[table,setTable]=useState(''),[offset,setOffset]=useState(0);
  const [detail,setDetail]=useState<ActivityEvent|null>(null);
  const params=new URLSearchParams({from,to,offset:String(offset),...(userId?{userId}:{}),...(table?{table}:{})});
  const report=useCQuery<ActivityReport>(['activity-report',params.toString()],'/api/reports/activity?'+params,{refetchOnWindowFocus:true});
  const allMembers=useCQuery<{items:{id:string;name:string}[]}>(['workspace-members'],'/api/workspace/members');
  const data=report.data;
  const peakEvents=Math.max(1,...(data?.daily.map(d=>d.events)??[])),peakSeconds=Math.max(1,...(data?.daily.map(d=>d.seconds)??[]));
  const peakPeople=Math.max(1,...(data?.users.map(u=>u.events)??[]));
  function change(fn:()=>void){fn();setOffset(0);}
  return <>
    <PageHeader title="Yönetim ve faaliyet raporu" description="Kim, ne zaman, hangi kaydı değiştirdi? Görev süreleri ve saha puantajı ile birlikte inceleyin."
      actions={<><Button size="sm" onClick={()=>window.print()}><Printer className="size-4" aria-hidden />Yazdır</Button><Button size="sm" disabled={!data} onClick={()=>saveBlob(new Blob([JSON.stringify({company:company.name,range:{from,to},...data},null,2)],{type:'application/json'}),`faaliyet-${from}-${to}.json`)}><Download className="size-4" aria-hidden />Görünümü indir</Button></>} />
    <Card className="mb-5"><div className="grid gap-3 p-5 sm:grid-cols-2 xl:grid-cols-4">
      <label className="text-xs text-muted">Başlangıç<Input type="date" required value={from} max={to} onChange={e=>change(()=>setFrom(e.target.value))} /></label>
      <label className="text-xs text-muted">Bitiş<Input type="date" required value={to} min={from} onChange={e=>change(()=>setTo(e.target.value))} /></label>
      <label className="text-xs text-muted">Kullanıcı<Select value={userId} onChange={e=>change(()=>setUserId(e.target.value))}><option value="">Tüm kullanıcılar</option>{allMembers.data?.items.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</Select></label>
      <label className="text-xs text-muted">Kayıt türü<Select value={table} onChange={e=>change(()=>setTable(e.target.value))}><option value="">Tüm izinli kayıtlar</option>{[...new Set([...(data?.tables.map(t=>t.table)??[]),...(table?[table]:[])])].map(t=><option key={t} value={t}>{tableLabels[t]??t}</option>)}</Select></label>
    </div></Card>
    {report.error && <Callout tone="danger">{report.error.message}</Callout>}
    {report.isPending && <PageLoading />}
    {data && <div className="space-y-5">
      <section aria-label="Faaliyet özeti" className="grid grid-cols-2 overflow-hidden rounded-2xl border border-border bg-surface lg:grid-cols-4">
        {[
          {label:'Kayıt hareketi',value:data.summary.events,icon:Activity}, {label:'İşlem yapan kişi',value:data.summary.people,icon:UsersRound},
          {label:'Görev çalışma süresi',value:duration(data.summary.seconds),icon:Clock3}, {label:'Tamamlanan görev',value:data.summary.completedTasks,icon:CheckCircle2},
        ].map((s,i)=><div key={s.label} className={`min-w-0 border-border p-5 ${i%2?'border-l':''} ${i>1?'border-t lg:border-t-0 lg:border-l':''}`}><p className="flex items-center justify-between gap-2 text-[10px] uppercase tracking-wider text-muted">{s.label}<s.icon className="size-4" aria-hidden /></p><p className="mt-2 break-words text-[26px] tabular-nums">{s.value}</p></div>)}
      </section>
      <p className="text-xs text-muted">Saatler açık görev sayaçlarından hesaplanır. Kayıt hareketi sayısı bir çalışma süresi veya verimlilik puanı değildir. Yalnızca erişiminizdeki modüller raporlanır; puantaj filtresi kaydı giren kullanıcıyı belirtir.</p>
      <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1.6fr)_minmax(0,1fr)]">
        <Card className="min-w-0 overflow-hidden"><CardHeader title="Günlük hareket ve çalışma" description="Bir günü seçerek o günün kayıtlarını inceleyin." /><div className="overflow-x-auto p-5"><div className="flex h-44 min-w-max items-end gap-1" role="group" aria-label="Günlük faaliyet grafiği">
          {data.daily.map(d=><button key={d.date} type="button" title={`${formatDateTR(d.date)}: ${d.events} hareket, ${duration(d.seconds)}`} aria-label={`${formatDateTR(d.date)}: ${d.events} hareket, ${duration(d.seconds)}`} onClick={()=>change(()=>{setFrom(d.date);setTo(d.date);})} className="flex h-full w-7 shrink-0 flex-col justify-end gap-2 rounded-md px-1 hover:bg-surface-2">
            <span className="flex h-32 items-end justify-center gap-0.5"><span className="w-2 rounded-t-sm bg-brand" style={{height:`${d.events/peakEvents*100}%`,minHeight:d.events?3:0}} /><span className="w-2 rounded-t-sm bg-text/40" style={{height:`${d.seconds/peakSeconds*100}%`,minHeight:d.seconds?3:0}} /></span><span className="text-[10px] text-muted">{d.date.slice(8)}</span>
          </button>)}
        </div><div className="mt-3 flex flex-wrap gap-4 text-xs text-muted"><span className="flex items-center gap-1.5"><span className="size-2 rounded-sm bg-brand" />Kayıt hareketi (en çok {peakEvents})</span><span className="flex items-center gap-1.5"><span className="size-2 rounded-sm bg-text/40" />Çalışma süresi (en çok {duration(peakSeconds)})</span></div></div></Card>
        <Card className="min-w-0 overflow-hidden"><CardHeader title="Kullanıcı kırılımı" description="Kişiyi seçerek hareket geçmişini açın." /><div className="max-h-80 divide-y divide-border overflow-y-auto">
          {data.users.map(u=><button key={u.id} type="button" onClick={()=>change(()=>setUserId(u.id))} className="block w-full px-5 py-3 text-left hover:bg-surface-2"><div className="flex items-center justify-between gap-3 text-sm"><span className="truncate">{u.name}</span><span className="shrink-0 text-xs tabular-nums">{u.events} hareket</span></div><div className="my-2 h-1.5 overflow-hidden rounded-full bg-surface-2"><div className="h-full rounded-full bg-brand" style={{width:`${u.events/peakPeople*100}%`}} /></div><p className="text-xs text-muted">{duration(u.seconds)} · {u.completedTasks} görev tamamlandı</p></button>)}
        </div></Card>
      </div>
      <Card className="overflow-hidden"><CardHeader title="İşlem geçmişi" description="Kaydı açarak değişen alanları ve önceki/sonraki değerleri görün. Sistem tarafından oluşan hareketler ayrıca belirtilir." />
        {data.events.length ? <TableWrap className="rounded-none border-0"><Table><thead><Tr><Th>Zaman</Th><Th>Kullanıcı</Th><Th>Kayıt / işlem</Th><Th>Değişen alanlar</Th><Th><span className="sr-only">Detay</span></Th></Tr></thead><tbody>{data.events.map(e=><Tr key={e.id}><Td className="whitespace-nowrap text-xs tabular-nums">{when(e.at)}</Td><Td className="whitespace-nowrap">{e.userName??'Sistem'}</Td><Td><p className="text-sm">{tableLabels[e.table]??e.table}</p><div className="mt-1 flex items-center gap-2"><Badge tone={e.action.toUpperCase()==='DELETE'?'danger':'neutral'}>{actionLabels[e.action]??e.action}</Badge><span className="max-w-52 truncate text-xs text-muted">{e.title??e.rowId}</span></div></Td><Td className="max-w-64 text-xs text-muted">{e.changedFields.map(f=>fieldLabels[f]??f).join(', ')||'Bağlantı / sistem alanı'}</Td><Td><Button size="sm" variant="ghost" aria-label={`${e.userName??'Sistem'} ${tableLabels[e.table]??e.table} işlem detayını aç`} onClick={()=>setDetail(e)}>İncele<ArrowRight className="size-3.5" /></Button></Td></Tr>)}</tbody></Table></TableWrap> : <EmptyState title="Bu aralıkta kayıt hareketi yok" description="Tarih, kullanıcı veya kayıt türü filtresini değiştirebilirsiniz." icon={<Activity className="size-5" />} />}
        {(offset>0||data.hasMore) && <div className="flex items-center justify-between border-t border-border p-4"><Button size="sm" disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-100))}>Önceki</Button><span className="text-xs text-muted">{offset+1}–{offset+data.events.length}</span><Button size="sm" disabled={!data.hasMore} onClick={()=>setOffset(offset+100)}>Sonraki</Button></div>}
      </Card>
      <Card className="overflow-hidden"><CardHeader title="Görev çalışma kayıtları" description="En son 100 sayaç oturumu. Devam eden süreler 24 saat sınırıyla gösterilir." /><TableWrap className="rounded-none border-0"><Table><thead><Tr><Th>Görev</Th><Th>Kullanıcı</Th><Th>Başlangıç / bitiş</Th><Th num>Süre</Th></Tr></thead><tbody>{data.sessions.map(s=><Tr key={s.id}><Td><p>{s.title}</p>{s.note&&<p className="mt-1 text-xs text-muted">{s.note}</p>}</Td><Td>{s.userName}</Td><Td className="whitespace-nowrap text-xs"><p>{when(s.startedAt)}</p><p className="mt-1 text-muted">{s.stoppedAt?when(s.stoppedAt):'Devam ediyor'}</p></Td><Td num>{duration(s.seconds)}</Td></Tr>)}</tbody></Table></TableWrap>{!data.sessions.length&&<p className="p-5 text-sm text-muted">Bu aralıkta kaydedilmiş görev süresi yok.</p>}</Card>
      <Card className="overflow-hidden"><CardHeader title="Personel / proje puantajı" description="Girilen puantaj saatleri; görev sayaçlarına eklenmez. En fazla 1.000 personel/proje grubu gösterilir." /><TableWrap className="rounded-none border-0"><Table><thead><Tr><Th>Personel</Th><Th>Proje</Th><Th num>Gün</Th><Th num>Normal saat</Th><Th num>Fazla mesai</Th></Tr></thead><tbody>{data.attendance.map((a,i)=><Tr key={a.employeeId+':'+i}><Td>{a.name}</Td><Td>{a.projectName??'Proje atanmamış'}</Td><Td num>{a.days}</Td><Td num>{a.normalHours}</Td><Td num>{a.overtimeHours}</Td></Tr>)}</tbody></Table></TableWrap>{!data.attendance.length&&<p className="p-5 text-sm text-muted">Bu aralıkta görüntüleyebileceğiniz puantaj kaydı yok.</p>}</Card>
    </div>}
    <Sheet open={!!detail} onOpenChange={v=>{if(!v)setDetail(null);}} title="İşlem ayrıntısı" description={detail ? `${tableLabels[detail.table]??detail.table} · ${when(detail.at)}` : ''}>
      {detail&&<div className="space-y-5"><dl className="grid grid-cols-2 gap-4 text-sm"><div><dt className="text-xs text-muted">Kullanıcı</dt><dd>{detail.userName??'Sistem'}</dd></div><div><dt className="text-xs text-muted">İşlem</dt><dd>{actionLabels[detail.action]??detail.action}</dd></div><div className="col-span-2"><dt className="text-xs text-muted">Kayıt kimliği</dt><dd className="break-all font-mono text-xs">{detail.rowId}</dd></div></dl>{source(detail)&&<Link to={source(detail)!} className="link inline-flex items-center gap-2 text-sm">Kaynağı aç<ArrowRight className="size-4" /></Link>}
        <div className="divide-y divide-border rounded-xl border border-border">{detail.changedFields.map(f=><div key={f} className="p-4"><p className="mb-2 text-xs text-muted">{fieldLabels[f]??f}</p><div className="grid grid-cols-2 gap-4 text-sm"><div><p className="mb-1 text-[10px] uppercase text-muted">Önce</p><p className="whitespace-pre-wrap break-all">{detailValue(detail.before[f])}</p></div><div><p className="mb-1 text-[10px] uppercase text-muted">Sonra</p><p className="whitespace-pre-wrap break-all">{detailValue(detail.after[f])}</p></div></div></div>)}</div><p className="text-xs text-muted">Gizli kimlik, parola, dosya içeriği ve erişiminiz dışındaki modüller rapora dahil edilmez.</p></div>}
    </Sheet>
  </>;
}
