import { sql } from 'drizzle-orm';
import { dec, roundMoney, todayIso, createSalesDocSchema } from '@erp/shared';
import type { Tx } from '../../db/client';
import { requireActiveWarehouse } from '../inventory/warehouses';
import { createJournalEntry, reverseJournalEntry, type AutoJournalLine } from '../ledger/journal';
import { openItemsFor } from '../parties/service';
import { createSalesDoc, transitionSalesDoc } from '../sales/orders';
import { all, one, newId, json, fail, mapped, journalLine, lockLeatherCosts, type LeatherCtx, type Row } from './common';
import { physicalMovement } from './movements';
import { issueProduction } from './production';
import { allocateCost } from './costs';
import { listSubcontracts, createSubcontract as createBaseSubcontract, listServiceCases, listCustomOrders, customAction as baseCustomAction } from './workflows';

export async function createSubcontract(tx:Tx,ctx:LeatherCtx,input:Row){
 if(!input.externalWarehouseId)throw fail('Fason işine işletmeye ait dış depo seçilmeli');await requireActiveWarehouse(tx,input.externalWarehouseId);
 const o=await one(tx,sql`select warehouse_id from leather_production_orders where id=${input.orderId}::uuid`);if(o.warehouse_id===input.externalWarehouseId)throw fail('Fason deposu üretim deposundan farklı olmalı');return createBaseSubcontract(tx,ctx,input);
}
export async function subcontractAction(tx:Tx,ctx:LeatherCtx,id:string,input:Row){
 await lockLeatherCosts(tx,ctx.companyId);const j=await one(tx,sql`select * from leather_subcontract_jobs where id=${id}::uuid for update`,'Fason işi');const o=await one(tx,sql`select * from leather_production_orders where id=${j.order_id} for update`);const actions:Row[]=j.config.actions??[];if(actions.some(a=>a.requestKey===input.requestKey))return(await listSubcontracts(tx)).find(r=>r.id===id)!;
 const external=j.config.externalWarehouseId;if(!external)throw fail('Fason dış depo bağlantısı gerekli');const materials=input.materials??[];let status=j.status;let returned=dec(j.returned_qty);const custody:Record<string,string>={...j.config.custody};let record:Row={};
 if(input.action==='cancel'){if(status!=='planned')throw fail('Sevk edilmiş fason işi malzeme çözülmeden iptal edilemez');status='cancelled';}
 else if(input.action==='dispatch'){
  if(status!=='planned'||!materials.length)throw fail('Planlanan fason sevkinde işletme malzemeleri gerekli');
  record=await physicalMovement(tx,ctx,{sourceType:'leather_subcontract',sourceId:id,date:input.date,warehouseId:o.warehouse_id,toWarehouseId:external,lines:materials,kind:'transfer',orderId:j.order_id});
  for(const l of materials)custody[l.itemId]=dec(custody[l.itemId]??0).plus(l.quantity).toFixed(4);
  // Move reservations with the company's material, preserving remaining firm demand.
  for(const l of materials){let left=dec(l.quantity);const reservations=await all(tx,sql`select * from leather_reservations where order_id=${j.order_id} and item_id=${l.itemId}::uuid and warehouse_id=${o.warehouse_id} and status='reserved' order by created_at for update`);for(const r of reservations){const remaining=dec(r.quantity).minus(r.consumed_qty);const moved=left.lt(remaining)?left:remaining;if(moved.lte(0))continue;if(moved.eq(remaining)&&dec(r.consumed_qty).isZero())await tx.execute(sql`update leather_reservations set warehouse_id=${external}::uuid where id=${r.id}`);else{await tx.execute(sql`update leather_reservations set quantity=quantity-${moved.toFixed(4)}::numeric where id=${r.id}`);await tx.execute(sql`insert into leather_reservations(id,company_id,created_by,order_id,item_id,piece_id,warehouse_id,quantity,status) values(${newId()},${ctx.companyId},${ctx.userId},${j.order_id},${l.itemId},${r.piece_id},${external},${moved.toFixed(4)},'reserved')`);}left=left.minus(moved);if(left.isZero())break;}}
  status='dispatched';
 }else{
  if(status!=='dispatched')throw fail('Fason tüketim/dönüş sevk edilmiş işte yapılır');
  for(const l of materials){if(dec(l.quantity).gt(custody[l.itemId]??0))throw fail('Fason malzeme işlemi bu işin sevk bakiyesini aşamaz');custody[l.itemId]=dec(custody[l.itemId]).minus(l.quantity).toFixed(4);}
  if(input.action==='consume'){if(!materials.length)throw fail('Fason tüketim satırları gerekli');const d=await issueProduction(tx,ctx,j.order_id,{date:input.date,requestKey:input.requestKey,note:input.note,lines:materials},{issueWarehouseId:external,subcontractId:id});record={productionDocumentId:d.id,stockDocumentId:d.stock_document_id,journalEntryId:d.journal_entry_id};}
  else if(input.action==='waste'){if(!materials.length)throw fail('Fason fire satırları gerekli');record=await physicalMovement(tx,ctx,{sourceType:'leather_subcontract',sourceId:id,date:input.date,warehouseId:external,lines:materials,kind:'waste',orderId:j.order_id});}
  else if(input.action==='return'){
   if(materials.length)record=await physicalMovement(tx,ctx,{sourceType:'leather_subcontract',sourceId:id,date:input.date,warehouseId:external,toWarehouseId:o.warehouse_id,lines:materials,kind:'transfer',orderId:j.order_id});
   if(input.quantity){returned=returned.plus(input.quantity);if(returned.gt(j.quantity))throw fail('Fasondan dönüş adedi iş miktarını aşamaz');}
   if(returned.eq(j.quantity)){if(Object.values(custody).some(q=>dec(q).gt(0)))throw fail('Fasondaki işletme malzemesini tüketin, iade alın veya fireyle çözümleyin');status='received';await tx.execute(sql`update leather_reservations set status='released' where order_id=${j.order_id} and warehouse_id=${external}::uuid and status='reserved'`);}
   for(const l of materials)await tx.execute(sql`update leather_reservations set warehouse_id=${o.warehouse_id} where order_id=${j.order_id} and item_id=${l.itemId}::uuid and warehouse_id=${external}::uuid and status='reserved' and consumed_qty=0`);
  }else throw fail('Fason işlemi geçersiz');
 }
 if(input.sourceJournalLineId&&input.cost)await allocateCost(tx,ctx,{orderId:j.order_id,sourceJournalLineId:input.sourceJournalLineId,amount:input.cost,kind:'subcontract',date:input.date,requestKey:input.requestKey,note:input.note});actions.push({...input,...record});await tx.execute(sql`update leather_subcontract_jobs set status=${status},returned_qty=${returned.toFixed(4)},config=config || ${json({actions,custody})} where id=${id}::uuid`);return(await listSubcontracts(tx)).find(r=>r.id===id)!;
}
export async function serviceAction(tx:Tx,ctx:LeatherCtx,id:string,input:Row){
 await lockLeatherCosts(tx,ctx.companyId);const c=await one(tx,sql`select * from leather_service_cases where id=${id}::uuid for update`,'Servis kaydı');const history:Row[]=c.config.history??[];if(history.some(h=>h.requestKey===input.requestKey))return(await listServiceCases(tx)).find(s=>s.id===id)!;
 const allowed:Record<string,string[]>={diagnose:['received'],approve_repair:['diagnosed'],repair:['approved','repairing'],ready:['approved','repairing'],deliver:['ready'],cancel:['received','diagnosed','approved']};if(!allowed[input.action]?.includes(c.status))throw fail('Servis durum geçişi uygun değil');
 const fee=input.action==='diagnose'?input.fee:c.config.fee??'0';if(c.config.warranty&&dec(fee).gt(0))throw fail('Garanti kapsamındaki servis ücretlendirilemez');if(input.action==='approve_repair'&&!input.approvalReference?.trim())throw fail('Müşterinin onay belge/iletişim referansı gerekli');
 let invoiceId=c.invoice_id;let record:Row={};let partsCost=dec(c.config.partsCost??0);if(input.parts?.length){if(input.action!=='repair'||!input.warehouseId)throw fail('Parça sarfı müşteri onayından sonra onarımda ve seçili depodan yapılır');record=await physicalMovement(tx,ctx,{sourceType:'leather_service',sourceId:id,date:input.date,warehouseId:input.warehouseId,lines:input.parts,kind:'issue'});partsCost=partsCost.plus(record.value);}
 if(input.invoiceId){const inv=await one(tx,sql`select * from invoices where id=${input.invoiceId}::uuid`,'Servis faturası');if(inv.party_id!==c.party_id||inv.status!=='posted'||inv.type!=='sales')throw fail('Servis için aynı müşterinin kayıtlı satış faturası gerekli');const billed=await one(tx,sql`select coalesce(sum(l.net),0)::text as net from invoice_lines l left join items i on i.id=l.item_id where l.invoice_id=${inv.id} and (l.item_id is null or i.kind='service')`);if(dec(billed.net).lt(fee))throw fail('Servis faturasında onaylı servis ücretini karşılayan hizmet satırı gerekli');invoiceId=inv.id;}
 if(input.action==='deliver'&&dec(fee).gt(0)&&!invoiceId)throw fail('Ücretli servis tesliminde fatura gerekli');const status:Record<string,string>={diagnose:'diagnosed',approve_repair:'approved',repair:'repairing',ready:'ready',deliver:'delivered',cancel:'cancelled'};history.push({...input,...record});await tx.execute(sql`update leather_service_cases set status=${status[input.action]},invoice_id=${invoiceId},config=config || ${json({assessment:input.assessment||c.config.assessment,fee,partsCost:partsCost.toFixed(2),history,lastActionDate:input.date,...(input.action==='approve_repair'?{customerApproval:{reference:input.approvalReference,date:input.date,recordedBy:ctx.userId}}:{})})} where id=${id}::uuid`);return(await listServiceCases(tx)).find(s=>s.id===id)!;
}
async function settleDeposit(tx:Tx,ctx:LeatherCtx,order:Row,invoiceId:string){
 if(!order.deposit_transaction_id)return;const active=await all(tx,sql`select d.id from leather_deposit_settlements d join journal_entries e on e.id=d.entry_id where d.deposit_transaction_id=${order.deposit_transaction_id} and e.reversed_by_id is null`);if(active.length)throw fail('Kapora başka faturaya mahsup edilmiş');
 const t=await one(tx,sql`select * from treasury_transactions where id=${order.deposit_transaction_id} for update`);const inv=await one(tx,sql`select * from invoices where id=${invoiceId}::uuid`);if(t.status!=='posted'||t.currency_code!==inv.currency_code||t.party_id!==order.party_id)throw fail('Kapora aynı müşteri ve fatura para biriminde kayıtlı olmalı');
 const receivable=await mapped(tx,'receivable');const charge=await one(tx,sql`select l.* from journal_lines l join journal_entries e on e.id=l.entry_id where e.source_type='invoice' and e.source_id=${inv.id} and e.reversal_of_id is null and l.account_id=${receivable}::uuid and l.party_id=${order.party_id} and l.debit>0 for update of l`,'Fatura müşteri borç kalemi');const open=(await openItemsFor(tx,order.party_id,'receivable',inv.invoice_date)).items.find(x=>x.lineId===charge.id);if(!open||dec(t.amount).gt(open.remaining))throw fail('Kapora faturanın açık müşteri borcunu aşamaz');
 const depositLine=await one(tx,sql`select l.* from journal_lines l join journal_entries e on e.id=l.entry_id where e.id=${t.journal_entry_id} and l.account_id=${await mapped(tx,'advance_received')}::uuid and l.credit>0`,'Avans muhasebe satırı');const amount=dec(t.amount);const settleBase=roundMoney(dec(charge.debit_base).times(amount).div(charge.debit));const depositBase=dec(depositLine.credit_base);const diff=depositBase.minus(settleBase);
 const lines:AutoJournalLine[]=[{accountId:depositLine.account_id,currency:depositLine.currency_code,fxRate:depositLine.fx_rate,debit:depositLine.credit,credit:'0',debitBase:depositBase.toFixed(2),creditBase:'0'}, {accountId:charge.account_id,partyId:order.party_id,currency:inv.currency_code,fxRate:charge.fx_rate,debit:'0',credit:amount.toFixed(2),debitBase:'0',creditBase:settleBase.toFixed(2)}];if(!diff.isZero())lines.push(journalLine(ctx,await mapped(tx,diff.gt(0)?'fx_gain':'fx_loss'),diff.neg()));
 const entry=await createJournalEntry(tx,ctx,{entryDate:inv.invoice_date,description:'Kişiye özel sipariş kapora mahsubu',lines,post:true},{source:{type:'leather_deposit_settlement',id:order.id}});const settled=await one(tx,sql`select id from journal_lines where entry_id=${entry.id} and account_id=${receivable}::uuid and credit>0`);await tx.execute(sql`insert into leather_deposit_settlements(id,company_id,created_by,custom_order_id,party_id,deposit_transaction_id,invoice_id,charge_line_id,settle_line_id,entry_id,amount,amount_base) values(${newId()},${ctx.companyId},${ctx.userId},${order.id},${order.party_id},${t.id},${inv.id},${charge.id},${settled.id},${entry.id},${amount.toFixed(2)},${settleBase.toFixed(2)})`);
}
export async function customAction(tx:Tx,ctx:LeatherCtx,id:string,input:Row){
 await lockLeatherCosts(tx,ctx.companyId);const o=await one(tx,sql`select * from leather_custom_orders where id=${id}::uuid for update`);if(o.status==='delivered'&&input.action==='deliver'&&o.invoice_id===input.invoiceId)return(await listCustomOrders(tx)).find(x=>x.id===id)!;
 await baseCustomAction(tx,ctx,id,input);
 if(input.action==='confirm'){
  const v=await one(tx,sql`select item_id from leather_variants where id=${o.variant_id}`);const salesOrderId=await createSalesDoc(tx,ctx,createSalesDocSchema.parse({kind:'order',partyId:o.party_id,docDate:todayIso(),deliveryDate:o.due_date,currency:o.config.currency,vatIncluded:false,notes:[o.config.customerNotes,o.config.monogram].filter(Boolean).join(' / '),lines:[{itemId:v.item_id,quantity:o.quantity,unitPrice:o.config.unitPrice,discountPct:'0'}]}));await transitionSalesDoc(tx,ctx,salesOrderId,'confirmed');const salesLine=await one(tx,sql`select id from sales_order_lines where order_id=${salesOrderId} order by line_no limit 1`);await tx.execute(sql`update leather_custom_orders set config=config || ${json({salesOrderId,salesOrderLineId:salesLine.id})} where id=${id}::uuid`);
 }else if(input.action==='cancel'&&o.config.salesOrderId)await transitionSalesDoc(tx,ctx,o.config.salesOrderId,'cancelled',input.note||'Kişiye özel sipariş iptali');
 else if(input.action==='deliver'){
  const order=await one(tx,sql`select * from leather_custom_orders where id=${id}::uuid`);if(!order.config.salesOrderId)throw fail('Ortak satış siparişi bağlantısı bulunamadı');const linked=await one(tx,sql`select coalesce(sum(l.quantity),0)::text as qty from invoice_lines l join sales_order_lines s on s.id=l.sales_order_line_id where l.invoice_id=${input.invoiceId}::uuid and s.order_id=${order.config.salesOrderId}::uuid`);if(dec(linked.qty).lt(order.quantity))throw fail('Teslim faturası kişisel siparişin ortak satış sipariş satırına bağlanmalı');await settleDeposit(tx,ctx,order,input.invoiceId);
 }
 return(await listCustomOrders(tx)).find(x=>x.id===id)!;
}
/** Called before the core invoice reversal; original history stays immutable. */
export async function reverseCustomDepositForInvoice(tx:Tx,ctx:LeatherCtx,invoiceId:string,date:string):Promise<void>{
 await lockLeatherCosts(tx,ctx.companyId);const entries=await all(tx,sql`select d.*,e.reversed_by_id from leather_deposit_settlements d join journal_entries e on e.id=d.entry_id where d.invoice_id=${invoiceId}::uuid for update of e`);for(const d of entries)if(!d.reversed_by_id)await reverseJournalEntry(tx,ctx,d.entry_id,{entryDate:date,description:'Kişisel sipariş faturası iptalinde kapora mahsubu iadesi',source:{type:'leather_deposit_settlement_cancel',id:d.custom_order_id}});await tx.execute(sql`update leather_custom_orders set status='ready',invoice_id=null where invoice_id=${invoiceId}::uuid and status='delivered'`);
}
