export const PERMISSIONS = [
  'manufacturing.catalog.read',
  'manufacturing.catalog.manage',
  'manufacturing.mrp.read',
  'manufacturing.mrp.manage',
  'manufacturing.production.read',
  'manufacturing.production.manage',
  'manufacturing.planning.read',
  'manufacturing.planning.manage',
  'manufacturing.quality.read',
  'manufacturing.quality.manage',
  'manufacturing.subcontracting.read',
  'manufacturing.subcontracting.manage',
  'manufacturing.maintenance.read',
  'manufacturing.maintenance.manage',
  'manufacturing.costs.read',
  'manufacturing.costs.manage',
  'inventory.wms.read',
  'inventory.wms.manage',
  'sales.logistics.read',
  'sales.logistics.manage',
  'core.integrations.read',
  'core.integrations.manage',
  'manufacturing.catalog.approve',
  'manufacturing.production.approve',
  'manufacturing.quality.approve',
  'manufacturing.planning.approve',
  'workspace.use',
  'company.manage',
  'members.manage',
  'settings.read',
  'settings.manage',
  'rates.manage',
  'accounts.manage',
  'ledger.read',
  'ledger.post',
  'ledger.close_period',
  // Yıl sonu kapanışı ve devir (kapanış fişi, yılı kilitleme, yeniden açma): yalnızca sahip ve yönetici; muhasebeci durumu okur (ledger.read)
  'ledger.yearend',
  'parties.read',
  'parties.manage',
  'inventory.read',
  'inventory.manage',
  'inventory.move',
  'invoices.read',
  'invoices.manage',
  'invoices.post',
  'deliveries.read',
  'deliveries.manage',
  'deliveries.post',
  'treasury.read',
  'treasury.manage',
  'treasury.post',
  'reports.read',
  // Çoklu şirket konsolidasyonu (Faz X7): birden çok şirketin verisini bir arada gösterir; yalnızca sahip ve yönetici
  'reports.consolidation',
  'data.export',
  'projects.read',
  'projects.manage',
  'projects.budget',
  'subcontracts.read',
  'subcontracts.manage',
  'subcontracts.approve',
  'procurement.read',
  'procurement.manage',
  'procurement.approve',
  'realestate.read',
  'realestate.manage',
  'realestate.approve',
  // İnsan kaynakları ve kişisel veri (Faz D)
  'hr.read',
  'hr.manage',
  'hr.sensitive',
  'privacy.manage',
  // Bordro (Faz D3): ücret verisi hr.sensitive'ten ayrı, ayrı izinle açılır
  'hr.payroll',
  'hr.payroll_manage',
  // Rehber ve ajanda (Faz X6): üçüncü kişilerin kişisel verisi içerir; izleyici rolüne verilmez
  'directory.read',
  'directory.manage',
  'leather.catalog.read',
  'leather.catalog.manage',
  'leather.catalog.approve',
  'leather.materials.read',
  'leather.materials.manage',
  'leather.production.read',
  'leather.production.manage',
  'leather.production.approve',
  'leather.costs.read',
  'leather.costs.manage',
  'leather.quality.read',
  'leather.quality.manage',
  'leather.quality.approve',
  'leather.subcontracting.read',
  'leather.subcontracting.manage',
  'leather.service.read',
  'leather.service.manage',
  'pos.read',
  'pos.sell',
  'pos.manage',
  'pos.approve',
] as const;
export type Permission = (typeof PERMISSIONS)[number];

export const ROLES = ['owner', 'admin', 'accountant', 'sales', 'site_manager', 'viewer', 'operations_manager', 'operator'] as const;
export type Role = (typeof ROLES)[number];

/**
 * MVP'de roller kod içinde hazır şablonlardır. Özel rol tablosu, ilgili modüller
 * (satış, şantiye) eklendiğinde ve gerçekten ihtiyaç doğduğunda gelecek.
 */
export const ROLE_PERMISSIONS: Record<Role, readonly Permission[]> = {
  owner: PERMISSIONS,
  admin: PERMISSIONS.filter((p) => p !== 'company.manage'),
  accountant: [
    'manufacturing.costs.read', 'manufacturing.costs.manage', 'manufacturing.production.read','workspace.use',
    'leather.costs.read',
    'leather.costs.manage',
    'leather.catalog.read',
    'leather.materials.read',
    'leather.production.read',
    'leather.subcontracting.read',
    'leather.quality.read',
    'leather.service.read',
    'pos.read',
    'settings.read',
    'rates.manage',
    'accounts.manage',
    'ledger.read',
    'ledger.post',
    'ledger.close_period',
    'parties.read',
    'parties.manage',
    'inventory.read',
    'inventory.manage',
    'inventory.move',
    'invoices.read',
    'invoices.manage',
    'invoices.post',
    'deliveries.read',
    'deliveries.manage',
    'deliveries.post',
    'treasury.read',
    'treasury.manage',
    'treasury.post',
    'reports.read',
    'data.export',
    'projects.read',
    'projects.manage',
    'projects.budget',
    'subcontracts.read',
    'subcontracts.manage',
    'subcontracts.approve',
    'procurement.read',
    'procurement.manage',
    'procurement.approve',
    'realestate.read',
    'realestate.manage',
    'realestate.approve',
    'hr.read',
    'hr.payroll',
    'hr.payroll_manage',
    'directory.read',
  ],
  // Satış temsilcisi: müşteri kartı ve cari hareketleri yönetir (kapsam belgesi, Modül 13)
  // Faturayı taslak olarak hazırlar; muhasebeleştirmeyi (invoices.post) muhasebeci yapar.
  // İrsaliyeyi de taslak olarak hazırlar; stok hareketini işleyen (deliveries.post) depo/şantiye/muhasebedir.
  sales: ['workspace.use', 
    'settings.read',
    'parties.read',
    'parties.manage',
    'inventory.read',
    'inventory.manage',
    'invoices.read',
    'invoices.manage',
    'deliveries.read',
    'deliveries.manage',
    'directory.read',
    'directory.manage',
  ],
  // Şantiye sorumlusu: malzeme sarfı/transferi/sayım girer, stok kartı açmaz; mal kabul (alış irsaliyesi)
  // ve sevk irsaliyesi işler, faturaya dokunmaz.
  // Proje: şantiye şefi proje/iş kalemi/ilerleme girer; bütçeyi (projects.budget) muhasebe/yönetim onaylar.
  site_manager: ['workspace.use', 
    'settings.read',
    // Yalnızca okuma: irsaliye, satın alma siparişi ve taşeron sözleşmesindeki cari seçicileri için (cari ekleyemez/değiştiremez)
    'parties.read',
    'inventory.read',
    'inventory.move',
    'deliveries.read',
    'deliveries.manage',
    'deliveries.post',
    'projects.read',
    'projects.manage',
    'subcontracts.read',
    'subcontracts.manage',
    'procurement.read',
    'procurement.manage',
    'realestate.read',
    'directory.read',
    'directory.manage',
  ],
  viewer: ['workspace.use', 'settings.read', 'ledger.read', 'parties.read', 'inventory.read', 'invoices.read', 'deliveries.read', 'treasury.read', 'reports.read', 'projects.read', 'subcontracts.read', 'procurement.read', 'realestate.read'],
  operations_manager: [
    'manufacturing.catalog.read',
    'manufacturing.catalog.manage',
    'manufacturing.mrp.read',
    'manufacturing.mrp.manage',
    'manufacturing.production.read',
    'manufacturing.production.manage',
    'manufacturing.planning.read',
    'manufacturing.planning.manage',
    'manufacturing.quality.read',
    'manufacturing.quality.manage',
    'manufacturing.subcontracting.read',
    'manufacturing.subcontracting.manage',
    'manufacturing.maintenance.read',
    'manufacturing.maintenance.manage',
    'inventory.wms.read',
    'inventory.wms.manage',
    'sales.logistics.read',
    'sales.logistics.manage',
    'manufacturing.catalog.approve',
    'manufacturing.production.approve',
    'manufacturing.quality.approve',
    'manufacturing.planning.approve','workspace.use', 'settings.read', 'parties.read', 'inventory.read', 'inventory.move', 'deliveries.read', 'deliveries.manage', 'deliveries.post', 'procurement.read', 'procurement.manage', 'procurement.approve', 'directory.read', 'directory.manage', 'leather.catalog.read', 'leather.catalog.manage', 'leather.catalog.approve', 'leather.materials.read', 'leather.materials.manage', 'leather.production.read', 'leather.production.manage', 'leather.production.approve', 'leather.costs.read', 'leather.costs.manage', 'leather.quality.read', 'leather.quality.manage', 'leather.quality.approve', 'leather.subcontracting.read', 'leather.subcontracting.manage', 'leather.service.read', 'leather.service.manage', 'pos.read', 'pos.sell', 'pos.manage', 'pos.approve'],
  operator: ['workspace.use', 'settings.read'],
};

/** Bir üyenin ETKİN izin kümesi (rol şablonu + kullanıcı bazlı modül erişimi); `effectivePermissions` üretir. */
export type PermissionSet = ReadonlySet<Permission>;

/**
 * İzin denetiminin TEK kapısı: istek bağlamındaki etkin izin kümesine bakar. Rol şablonuna doğrudan bakmak (kullanıcı bazlı
 * modül erişimini atlatır) yasaktır; yalnızca `roleHasDefault` (rol varsayılanı, arayüzde ipucu göstermek için) vardır ve
 * test/access-scan.test.ts kaynakta başka yerde kullanılmadığını doğrular.
 */
export function hasPermission(permissions: PermissionSet, permission: Permission): boolean {
  return permissions.has(permission);
}

/** Rol şablonunun varsayılanı (kullanıcı istisnası YOK). Yalnızca varsayılan/ipucu hesapları ve testler için. */
export function roleHasDefault(role: Role, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role].includes(permission);
}
