import { beforeAll, describe, expect, it } from 'vitest';
import type { FastifyInstance } from 'fastify';
import { randomUUID } from 'node:crypto';
import { addMember, client, createCompany, makeApp, registerUser } from './helpers';

let app:FastifyInstance;
beforeAll(async()=>{app=(await makeApp()).app;});
describe('Çalışma alanı',()=>{
  it('saha tekrar gönderimi, proje izolasyonu ve program bağımlılıkları',async()=>{
    const user=await registerUser(app,'Ops');const company=await createCompany(app,user.token);const c=client(app,user.token,company.id);
    const project=(await c.post('/api/projects',{code:'OPS',name:'Saha projesi',kind:'own'})).json().project;
    const body={id:randomUUID(),kind:'site_report',title:'Günlük imalat',projectId:project.id,eventDate:'2026-10-05',dueDate:'2026-10-06',payload:{workers:4,workDone:'Beton döküldü'}};
    const created=await c.post('/api/workspace/operations',body);expect(created.statusCode,created.body).toBe(201);
    const replay=await c.post('/api/workspace/operations',body);expect(replay.statusCode,replay.body).toBe(200);expect(replay.json().replayed).toBe(true);
    expect((await c.post('/api/workspace/operations',{...body,title:'Farklı imalat'})).statusCode).toBe(409);
    const aBody={kind:'schedule',title:'Kalıp işleri',projectId:project.id,eventDate:'2026-10-05',dueDate:'2026-10-06',payload:{start:'2026-10-05',end:'2026-10-06',progress:0,dependencies:[]}};
    const a=await c.post('/api/workspace/operations',aBody);expect(a.statusCode,a.body).toBe(201);
    const b=await c.post('/api/workspace/operations',{...aBody,title:'Beton işleri',payload:{...aBody.payload,dependencies:[a.json().item.id]}});expect(b.statusCode,b.body).toBe(201);
    const cycle=await c.put(`/api/workspace/operations/${a.json().item.id}`,{...aBody,version:1,status:'open',payload:{...aBody.payload,dependencies:[b.json().item.id]}});expect(cycle.statusCode,cycle.body).toBe(400);
    const foreignCompany=await createCompany(app,user.token);expect((await client(app,user.token,foreignCompany.id).get(`/api/workspace/schedule/${project.id}`)).statusCode).toBe(404);
    const site=await addMember(app,c,company.id,'site_manager');expect((await site.client.post('/api/workspace/operations',{kind:'collection',title:'İzinsiz takip',partyId:randomUUID(),eventDate:'2026-10-05',dueDate:'2026-10-05',payload:{promiseAmount:'10',currency:'TRY',promiseDate:'2026-10-05'}})).statusCode).toBe(403);
    expect((await c.get('/api/workspace/alerts')).statusCode).toBe(200);
    expect((await c.get('/api/workspace/setup')).statusCode).toBe(200);
    const scenario=await c.post('/api/workspace/cash-scenarios/preview',{name:'Gecikme',delayDays:30,outflowIncreasePct:15,weeks:13});expect(scenario.statusCode,scenario.body).toBe(200);
  });
  it('portal sadece seçilen cariyi gösterir; yanlış parola, belge ve iptal engellenir',async()=>{
    const user=await registerUser(app,'Portal');const company=await createCompany(app,user.token);const c=client(app,user.token,company.id);
    const party=await c.post('/api/parties',{code:'P001',name:'Portal müşterisi',kind:'customer'});expect(party.statusCode,party.body).toBe(201);
    const partyId=party.json().party.id;
    const other=await c.post('/api/parties',{code:'P002',name:'Gizli diğer müşteri',kind:'customer'});expect(other.statusCode,other.body).toBe(201);
    const password='Portal-Password-12345';
    const created=await c.post('/api/workspace/portal-links',{partyId,label:'Müşteri portalı',password,days:7});expect(created.statusCode,created.body).toBe(201);
    const credentials={token:created.json().token,password};
    const view=()=>app.inject({method:'POST',url:'/api/portal/view',payload:credentials});
    const viewed=await view();expect(viewed.statusCode,viewed.body).toBe(200);expect(viewed.json().party.name).toBe('Portal müşterisi');expect(viewed.body).not.toContain('Gizli diğer müşteri');
    expect((await app.inject({method:'POST',url:'/api/portal/view',payload:{...credentials,password:'wrong-password-123'}})).statusCode).toBe(401);
    expect((await app.inject({method:'POST',url:'/api/portal/view',payload:{...credentials,documentId:randomUUID()}})).statusCode).toBe(404);
    const revoke=await c.post(`/api/workspace/portal-links/${created.json().id}/revoke`);expect(revoke.statusCode,revoke.body).toBe(200);expect((await view()).statusCode).toBe(401);
  });
  it('görev izolasyonu, atama ve eşzamanlı düzenleme koruması',async()=>{
    const user=await registerUser(app,'Work');
    const company=await createCompany(app,user.token);
    const c=client(app,user.token,company.id);
    const other=await createCompany(app,user.token);
    const sales=await addMember(app,c,company.id,'sales');
    const created=await c.post('/api/workspace/tasks',{title:'Dekont kontrolü',dueDate:'2026-10-10'});
    expect(created.statusCode,created.body).toBe(201);
    const task=created.json().item;
    expect((await sales.client.get('/api/workspace/tasks')).json().items).toHaveLength(0);
    expect((await client(app,user.token,other.id).patch(`/api/workspace/tasks/${task.id}`,{status:'done',version:1})).statusCode).toBe(404);
    expect((await c.patch(`/api/workspace/tasks/${task.id}`,{status:'done',version:1})).statusCode).toBe(200);
    expect((await c.patch(`/api/workspace/tasks/${task.id}`,{status:'open',version:1})).statusCode).toBe(409);
    expect((await sales.client.post('/api/workspace/tasks',{title:'Atama',dueDate:'2026-10-10',ownerId:user.userId})).statusCode).toBe(403);
    const assigned=await c.post('/api/workspace/tasks',{title:'Satış takibi',dueDate:'2026-10-10',ownerId:sales.userId});
    expect(assigned.statusCode,assigned.body).toBe(201);
    expect((await sales.client.get('/api/workspace/tasks')).json().items).toHaveLength(1);
  });
  it('belge sürümleri ve bağlı kayıt erişimi; yabancı şirket engeli',async()=>{
    const user=await registerUser(app,'Doc');
    const company=await createCompany(app,user.token);
    const c=client(app,user.token,company.id);
    const project=await c.post('/api/projects',{code:'DOC',name:'Belge projesi',kind:'own'});
    expect(project.statusCode,project.body).toBe(201);
    const id=project.json().project.id;
    const body={record:{kind:'project',id},filename:'sozlesme.pdf',mime:'application/pdf',base64:Buffer.from('%PDF-1.7\n%%EOF').toString('base64')};
    const uploaded=await c.post('/api/workspace/documents',body);
    expect(uploaded.statusCode,uploaded.body).toBe(201);
    const documentId=uploaded.json().id;
    const version=await c.post('/api/workspace/documents',{...body,previousId:documentId});
    expect(version.statusCode,version.body).toBe(201);
    expect((await c.post('/api/workspace/documents',{...body,previousId:documentId})).statusCode).toBe(409);
    expect((await c.get(`/api/workspace/documents/${documentId}/download`)).statusCode).toBe(200);
    const sales=await addMember(app,c,company.id,'sales');
    expect((await sales.client.get(`/api/workspace/documents/${documentId}/download`)).statusCode).toBe(403);
    expect((await sales.client.get('/api/workspace/search?q=DOC')).json().items).toHaveLength(0);
    const other=await createCompany(app,user.token);
    const oc=client(app,user.token,other.id);
    expect((await oc.get(`/api/workspace/documents/${documentId}/download`)).statusCode).toBe(404);
    expect((await oc.post('/api/workspace/documents',body)).statusCode).toBe(404);
    expect((await c.post('/api/workspace/documents',{...body,base64:Buffer.from('not a PDF').toString('base64')})).statusCode).toBe(400);
  });
});
