import {
  ArrowLeftRight,
  BarChart3,
  BookMarked,
  BookOpen,
  Boxes,
  Building2,
  CalendarDays,
  Circle,
  ClipboardCheck,
  Contact,
  Coins,
  Download,
  FileText,
  Hourglass,
  Landmark,
  LayoutDashboard,
  Library,
  ListTree,
  Link2,
  Package,
  PackageCheck,
  Percent,
  Receipt,
  ReceiptText,
  Repeat,
  Scale,
  ShoppingBag,
  Tags,
  TrendingUp,
  Truck,
  Users,
  Wallet,
  Warehouse,
  type LucideIcon,
} from 'lucide-react';

/** Modül kaydındaki (shared) ikon adı -> bileşen */
const NAV_ICONS: Record<string, LucideIcon> = {
  'layout-dashboard': LayoutDashboard,
  'book-open': BookOpen,
  'list-tree': ListTree,
  scale: Scale,
  'file-text': FileText,
  coins: Coins,
  percent: Percent,
  'calendar-days': CalendarDays,
  tags: Tags,
  users: Users,
  'building-2': Building2,
  contact: Contact,
  hourglass: Hourglass,
  package: Package,
  boxes: Boxes,
  'arrow-left-right': ArrowLeftRight,
  'clipboard-check': ClipboardCheck,
  warehouse: Warehouse,
  receipt: Receipt,
  'receipt-text': ReceiptText,
  'link-2': Link2,
  truck: Truck,
  'package-check': PackageCheck,
  wallet: Wallet,
  landmark: Landmark,
  'book-marked': BookMarked,
  library: Library,
  'trending-up': TrendingUp,
  'shopping-bag': ShoppingBag,
  'bar-chart': BarChart3,
  repeat: Repeat,
  download: Download,
};

export const navIcon = (name: string): LucideIcon => NAV_ICONS[name] ?? Circle;
