import {
  ArrowLeftRight,
  BookOpen,
  Boxes,
  Building2,
  CalendarDays,
  Circle,
  ClipboardCheck,
  Contact,
  Coins,
  FileText,
  Hourglass,
  LayoutDashboard,
  ListTree,
  Package,
  Percent,
  Scale,
  Tags,
  Users,
  Warehouse,
  type LucideIcon,
} from 'lucide-react';

/** Modül kaydındaki (shared) ikon adı -> bileşen */
const NAV_ICONS: Record<string, LucideIcon> = {
  'layout-dashboard': LayoutDashboard,
  'book-open': BookOpen,
  'list-tree': ListTree,
  scale: Scale,
  'file-text': FileText,
  coins: Coins,
  percent: Percent,
  'calendar-days': CalendarDays,
  tags: Tags,
  users: Users,
  'building-2': Building2,
  contact: Contact,
  hourglass: Hourglass,
  package: Package,
  boxes: Boxes,
  'arrow-left-right': ArrowLeftRight,
  'clipboard-check': ClipboardCheck,
  warehouse: Warehouse,
};

export const navIcon = (name: string): LucideIcon => NAV_ICONS[name] ?? Circle;
